import { NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';

const FINNHUB_API_KEY = process.env.FINNHUB_API_KEY || 'demo';

// Server-side cache (5 minutes)
let cachedHeadlines: any[] | null = null;
let cacheTimestamp: number = 0;
const CACHE_DURATION = 5 * 60 * 1000;

// Key tickers to fetch company-specific news for
const KEY_TICKERS = ['NVDA', 'AAPL', 'TSLA', 'MSFT', 'META', 'AMZN', 'GOOGL', 'AMD', 'NFLX', 'COIN'];

// Fallback headlines when API fails or no key (updated 2026-05-15 13:00 UTC)
const FALLBACK_NEWS = [
  { headline: 'US equity index futures sharply lower Friday May 15 pre-market at 13:00 UTC with S&P 500 futures -1.2%, Nasdaq-100 futures -1.6% to 29,195.29 and Dow futures -440 points (-0.9%) per CNBC / ts2.tech — the risk-off rotation arriving the morning after Thursday\'s fresh-record close (S&P +0.77% / Nasdaq +0.88% / Dow +0.74% reclaiming 50,000) and reading the Trump-Xi Beijing summit wrap as cordial-but-thin on hard deliverables per CNBC\'s "three big takeaways": China committed to 200 Boeing 737 jets vs ~500 Wall Street expectation, USTR Greer flagged ≥$10B/year in Chinese ag purchases, a bilateral "Board of Trade" framework, Xi "expressed interest" in buying more US oil and the joint Hormuz-must-remain-open language — but Taiwan arms ruling deferred ("I will make a determination"), no firm Chinese commitment on Iran despite the Hormuz line, no tariff cuts and no rare-earths deal in the May summit add-on per Axios / Washington Times / IBTimes; INTC -4% pre-market on UBS server-CPU share data showing Q1 share at 54.9% (-370bps ceded to AMD/Arm), AMD -3% on cohort drag with EVP $10.83M insider sale flagged by Daily Political; 10Y Treasury yield ~4.54% near July-2025 high per Trading Economics, DXY at two-week high, Brent ~$108-109/bbl and WTI ~$108 holding bid on the joint Hormuz language and the structural Iran-war supply loss (~880M barrels cumulative, IEA flagging undersupply through October); 8:30 ET Empire State May print due (prior April +11 a 5-month high), Industrial Production / Capacity Utilization April at 9:15 ET, U Michigan May prelim sentiment 48.2 record-low with year-ahead inflation 4.5% (long-run 3.4%); Senate Banking CLARITY Act 15-9 bipartisan advance Thursday with Dem cross-overs Sens. Gallego and Alsobrooks per CoinDesk / CNBC, full Senate floor needs 60-vote cloture with Memorial Day recess May 21 the proximate deadline; first FOMC under new Chair Kevin Warsh (confirmed 54-45 Wed) is June 16-17 with CME FedWatch ~72% no-change through year-end and ~39% rate-HIKE odds still in the mix', category: 'general', related: '' },
  { headline: 'April Import Prices on the BLS tape from Thursday May 14 showed nonfuel industrial supplies +1.6% MoM — the largest 12-month rise since October 2022 — extending the Wednesday April PPI shocker (+1.4% MoM / +6.0% YoY, biggest YoY since Dec 2022, gas +15.6% MoM) and reinforcing the cost-pass-through-from-Iran-war signal that has driven Wall Street to fully price out 2026 cuts with ~39% rate-HIKE odds still in the curve per CNBC / Polymarket / 24-7 Wall St; U Michigan consumer sentiment had already printed at 48.2 a fresh RECORD LOW per CNBC, with year-ahead inflation expectations at 4.5% (down from 4.7%) and long-run 3.4% (down from 3.5%) — ~33% of consumers citing gas prices and ~30% citing tariffs as drivers; Friday May 15 macro calendar has Empire State Manufacturing May at 8:30 ET (prior April +11 a 5-month high vs forecast -0.5), Industrial Production / Capacity Utilization April at 9:15 ET (March +0.70% YoY, capacity util 75.7%) — alongside a U Mich May prelim release window through ~10am ET; new Fed Chair Kevin Warsh confirmed 54-45 Wednesday evening (closest-margin confirmation in the modern era, only Sen. Fetterman crossing from Democrats) chairs his first FOMC meeting June 16-17, Washington Post citing Trump allies who "warn rate cuts may have to wait" and Paul Tudor Jones telling CNBC May 7 "There\'s no chance Warsh will be able to get the Fed to cut rates" and may "want to consider raising" citing Warsh\'s historical "regime change" framing for the central bank; 10Y yield ~4.54% Friday near July-2025 high per Trading Economics, DXY at two-week high; Brent ~$108-109/bbl and WTI ~$108 holding bid on the Trump-Xi joint Hormuz-must-remain-open agreement plus Xi expressing interest in buying more US oil per CNBC summit takeaways with Aramco\'s Petroline bypass still running 7M bpd and IEA flagging undersupply through October even if conflict resolves next month; Russia-Ukraine overnight Kyiv strikes killing 24+ (incl. 3 children) with Zelensky preparing "response formats" per Kyiv Independent / CBS News the cross-asset geopolitical overlay; Senate Banking CLARITY Act 15-9 to full Senate the structural overlay with Memorial Day May 21 recess deadline', category: 'general', related: '' },
  { headline: 'Nvidia (NVDA) closed Thursday May 14 at $235.74 (+4.4%) with intraday high $236.54 and market cap $5.77 trillion per GuruFocus / TradingKey on overnight US Commerce H200-China-license grant — Trump cleared roughly 10 Chinese firms (Alibaba, Tencent, ByteDance, JD.com plus distributors Lenovo/Foxconn) to purchase H200 AI chips with each approved customer permitted up to 75,000 chips per CNBC; UBS raised the NVDA price target Friday to $275 from $245 with Buy reiterated, analyst Tim Arcuri writing "set-up for a good set of numbers and potentially positive news on capital return is a good one" — the Wall Street consensus PT now $258 with 41 analysts at Strong Buy and ~39% implied upside; the May 20 AMC fiscal-Q1 print (some trade-press sources citing May 27 — verify against IR page) the next-gating AI hardware catalyst, consensus revenue ~$78.8B (company guide $78B +/-2%) with Citi modeling +$1.4B upside to ~$80B and Goldman projecting ~$2B beat per GuruFocus, B300 ramp framing expected ~$89B Q2 revenue (+11% QoQ); the H200 PARADOX still in play with ZERO actual deliveries to China yet under Beijing pressure on national-champion firms to vet/block orders on national-security grounds per NAI 500 / BanklessTimes — license-grant introduces material 2H26 / FY27 upside ONLY if Beijing-side enforcement loosens, ByteDance reportedly shifting chip-spend to Huawei Ascend; CEO Jensen Huang was on the ground in Beijing as a late-add to Trump\'s 16-CEO delegation per Bloomberg / SCMP / CNBC after Trump phoned Tuesday night following media coverage of Monday omission; CSCO +17% Thursday close on Q3 AI-infrastructure orders forecast raised to $9B from $5B annual on $5.3B YTD bookings per CNBC / Motley Fool the cross-cohort demand validation, AMD\'s May 5 blowout Q1 (EPS $1.37, Data Center +57% to $5.8B, Q2 guide $11.2B) the read-through that elevates the bar for May 20; Friday pre-market tilting lower with tech (-1.6% Nasdaq-100 futures per CNBC / ts2.tech), April PPI +1.4% MoM / +6.0% YoY and Warsh confirmed 54-45 the macro overhang, Trump-Xi Beijing summit wrap with 200 Boeing jets (vs ~500 expectation) and Taiwan arms ruling deferred the cross-asset frame', category: 'company', related: 'NVDA' },
  { headline: 'Apple (AAPL) added another ATH-area close Thursday May 14 with shares rangebound near $300 per MacDailyNews / Rolling Out — CEO Tim Cook on the ground in Beijing as part of Trump\'s 16-CEO delegation in what 9to5Mac framed as Cook\'s FINAL major diplomatic effort as CEO with September 1, 2026 handover to hardware chief John Ternus confirmed, Cook transitioning to executive chairman tasked with engaging policymakers and on App Store / AI-feature footprint continuity in China; the WSJ May 8 scoop confirmed Apple and Intel reached a preliminary chip-making agreement with Intel\'s 18A foundry the secondary option to longtime TSMC partner — Tom\'s Hardware confirms Intel will produce entry-level M-series silicon for select MacBook Air and iPad Pro models with volume production NOT until 2027-2029 on the 18A node, an estimated 15-20M units annually, with Apple reportedly eyeing the upcoming 18A-P for future iPhones per TrendForce; the prior-quarter print already booked the bull case ($111.18B rev +16.6% YoY record, $2.01 EPS +22%, iPhone $57B +22%, Greater China +28%, $100B buyback re-up); Trump-Xi Beijing summit closed Friday May 15 with Apple-relevant cross-asset frame — China committed 200 Boeing 737 jets (vs ~500 expectation, BA -4% Thursday), ≥$10B/year US ag purchases per USTR Greer, Treasury Secretary Bessent confirming "Board of Trade" framework for investment in non-sensitive areas, plus market-access discussions for US financial services in mainland China; cross-asset tape Friday risk-off pre-market with S&P 500 futures -1.2% / Nasdaq-100 -1.6% per CNBC / ts2.tech, INTC -4% pre-market on UBS server-CPU share data, NVDA H200 China license-grant overnight reshaping the AI cohort frame ahead of the May 20 AMC print, April PPI +1.4% MoM / +6.0% YoY and Warsh confirmed 54-45 the macro overhang, U Michigan May prelim 48.2 record-low sentiment; Russia-Ukraine overnight Kyiv strikes killing 24+ (incl. 3 children) and Israel-Lebanon Round 3 Washington talks with April 17 ceasefire formally expiring Sunday May 17 the multi-front geopolitical overlay', category: 'company', related: 'AAPL' },
  { headline: 'Intel (INTC) -4% pre-market Friday May 15 per CNBC futures tape — the largest single-name Nasdaq drag — on UBS server-CPU share data showing INTC Q1 2026 share at 54.9%, down 370 basis points sequentially ceded to AMD and Arm-based hyperscaler silicon; Mizuho separately raised INTC PT to $124 on May 12 per 24-7 Wall St on the agentic-AI server-demand turn validating the Lip-Bu Tan-led pivot, but the share-loss data has reframed Friday\'s tape against the prior week\'s optimism — INTC had reached an all-time intraday high $130.57 on the May 8 WSJ confirmation that Apple and Intel reached a preliminary chip-making agreement per Decrypt (vs the dot-com peak $74.88 from August 2000, ~74% above), Stocktwits modeled the Apple foundry deal at ~$10B annual sales by 2030 with BofA\'s $96 PT in place (from $56); Intel\'s 18A process node is now in MASS PRODUCTION with Panther Lake consumer chips shipping and yields ahead of internal projections per Tom\'s Hardware / Trefis, the foundry roster spanning Apple (entry M-series 2027+, ~15-20M units/year), Microsoft (Feb 2024), AWS (Sept 2024) AND Tesla/SpaceX (Musk\'s Austin "Terafab" $119B for 14A node) with FOUNDRY BREAK-EVEN expected 2027; US government as INTC\'s 10% largest shareholder under CEO Lip-Bu Tan the structural Trump-administration alignment running directly into Friday\'s Trump-Xi Beijing summit wrap which delivered the bilateral "Board of Trade" framework per Bessent but only 200 Boeing 737 jets vs ~500 expectation (BA -4% Thursday) and Taiwan arms ruling deferred ("I will make a determination") per CNBC / Axios summit takeaways; NVDA H200 China-license grant to ~10 Chinese firms overnight per CNBC the cross-cohort AI-policy easing tell, AMD -3% pre-market on cohort drag plus EVP $10.83M insider sale flagged by Daily Political, NVDA fiscal-Q1 May 20 AMC the next-gating AI catalyst, April PPI +1.4% MoM / +6.0% YoY and Warsh confirmed 54-45 the macro frame, U Michigan May prelim sentiment 48.2 record-low', category: 'company', related: 'INTC' },
  { headline: 'Tesla (TSLA) closed Thursday May 14 at $445.13 per FXLeaders / Stocktwits after +14% over the prior six sessions on China-FSD-rollout bets and Beijing-summit-access optimism with Musk part of Trump\'s 16-CEO delegation — but Friday pre-market tilting lower with tech (-1.6% Nasdaq-100 futures) as the Trump-Xi summit wrap delivered cordial language with few hard tech-specific deliverables per CNBC\'s "three big takeaways" (200 Boeing 737 jets vs ~500 expectation, ≥$10B/year US ag purchases, bilateral "Board of Trade," Hormuz must remain open) but NO Tesla-specific FSD-approval breakthrough announced — Musk\'s internal-team FSD-China rollout estimate having slipped to 2027 per Invezz from the prior Q3 2026 working estimate; Robotaxi operations now at 39 unsupervised vehicles (up from 9 start of April, 26 start of May) with Dallas + Houston launched April 2026 and Phoenix, Miami, Orlando, Tampa, Las Vegas planned for 1H 2026 per Motley Fool / 24-7 Wall St — but persistent operational glitches reported (long waits, "no rides available," confusing drop-offs, car shortage), Musk walked H1 2026 multi-city ramp back to "a dozen or so states by end of 2026," Cybercab production cadence ~2,000/week targeting 10,000/week by year-end with capex above $25B and negative FCF the rest of 2026; the Q1 update documented $22.39B revenue / $4.72B gross profit / $941M operating income / $44.74B cash-and-short-term-investments / 1.3M FSD subscriptions (+51% YoY); Panasonic battery production delays the proximate supply-chain overhang per 24-7 Wall St; cross-asset tape Friday risk-off pre-market per CNBC / ts2.tech, INTC -4% on UBS server-CPU share data, AMD -3% pre-market, NVDA H200 China license-grant overnight reshaping the chip-cohort frame ahead of May 20 AMC, April PPI +1.4% MoM / +6.0% YoY and Warsh confirmed 54-45 the macro overhang, U Michigan May prelim 48.2 record-low sentiment, Russia-Ukraine overnight Kyiv strikes killing 24+ the cross-asset geopolitical tell', category: 'company', related: 'TSLA' },
  { headline: 'Boeing (BA) closed Thursday May 14 down ~4% in the afternoon session per CNBC / USNews / Bloomberg after Trump told Fox News that China had agreed to buy 200 737 MAX jets — materially below the ~500-jet figure Jefferies / Bloomberg analysts had modeled into Day-2 of the Trump-Xi summit, the gap-vs-expectations overwhelming what otherwise would have been received as a major commercial breakthrough (the first major Chinese Boeing order in nearly a decade across the 737 MAX grounding, pandemic, US-China trade disputes and BA production / safety issues per Fortune / Bloomberg / USNews) — the 200-jet final deal represents ~3% of BA\'s ~6,719-aircraft backlog at end-March 2026, with NO details released on jet types or delivery timelines per BiggoNews; CEO Kelly Ortberg in Beijing as part of the Trump 16-CEO delegation per Bloomberg / Fortune / Skift / Motley Fool, Ortberg having previously confirmed the manufacturer reached a solution with Chinese airlines over critical spare-parts access (a prior trade-dispute obstacle), telling Bloomberg "without the administration\'s support, I don\'t think we\'ll see any near-term large orders out of China" — the 200-jet final deal worth multi-billions but the gap-vs-expectations cratered the print; Treasury Secretary Bessent confirmed the jet order alongside ≥$10B/year US ag purchase commitments per USTR Greer plus oil/LNG purchase language and the "Board of Trade" framework per CNBC / Axios summit takeaways, Xi separately delivering explicit Beijing pledges no weapons to Iran (ruling out surface-to-air missile transfers) AND Hormuz must remain open AND Xi committing to buy more US oil to reduce China dependence on the strait — but Trump-Xi summit closed Friday with Taiwan arms ruling deferred ("I will make a determination") and no rare-earths or tariff deal in the May add-on; chip-cohort tape Friday risk-off pre-market with S&P 500 futures -1.2% / Nasdaq-100 -1.6% per CNBC / ts2.tech, NVDA H200 China-export license-grant overnight, INTC -4% pre-market on UBS server-CPU share data, April PPI +1.4% MoM / +6.0% YoY and Warsh confirmed 54-45 the macro overhang, U Michigan May prelim 48.2 record-low sentiment, Russia-Ukraine overnight Kyiv strikes killing 24+ the geopolitical overlay', category: 'company', related: 'BA' },
  { headline: 'Coinbase (COIN) closed Thursday May 14 at $216.01 +10% (intraday range $195.10-$222.35, volume 10.31M vs avg 9.73M) — a three-month high per CryptoTimes / Benzinga / Stocktwits — as the Senate Banking Committee advanced the CLARITY Act 15-9 BIPARTISAN to the full Senate floor per CoinDesk / CNBC / TheStreet Crypto with Dem cross-overs Sens. Ruben Gallego and Angela Alsobrooks joining all committee Republicans, Chair Tim Scott calling the question after hours of partisan sniping; the bill writes statutory digital-commodity classification for assets like BTC and XRP (removing the legacy 2020 SEC-Ripple enforcement overhang), establishes a CFTC-primary regulatory regime for digital-commodity spot trading and DPP frameworks for digital-asset securities — Coinbase CEO Brian Armstrong saying the bill is "closer than ever" to becoming law, the White House targeting July 4, 2026 for signing per industry reporting, but Sen. Gillibrand referencing August as a likely date with the full Senate floor needing 60-vote cloture (7+ Democrats must cross), Memorial Day recess May 21 the proximate legislative deadline — Sen. Lummis having warned committee failure would push effective implementation to 2030 or beyond; the competitive landscape sharpened with CHARLES SCHWAB rolling out spot BTC AND ETH retail trading May 13 (Wednesday) at industry-low 75bps with Paxos execution/sub-custody and Schwab Premier Bank primary custodian per CoinDesk — analyst note framing 1% retail allocation against Schwab\'s $11.77T AUM as >$100B new spot capital over 12 months, Schwab clients already holding ~20% of all assets in US spot crypto ETPs per Investor Ideas; Brian Armstrong having hosted Wednesday lunch with Senate Republicans to whip the vote, Coinbase CLO Paul Grewal publicly clashing with ABA CEO Rob Nichols; analyst $220 next-target watch level per CryptoTimes; Friday pre-market tilting lower with broad tech (-1.6% Nasdaq-100 futures per CNBC) as BTC slipped back to $80,326.56 on Crypto.com tape (-0.69% 24h) after Thursday\'s reclaim of $81K — Strategy +6.6% Thursday on the same CLARITY catalyst, XRP +4.49% best major Thursday; April PPI +1.4% MoM / +6.0% YoY and Warsh confirmed 54-45 the macro overlay', category: 'company', related: 'COIN' },
  { headline: 'AMD traded -3% pre-market Friday May 15 per the chip-cohort drag with INTC -4% on UBS server-CPU share data showing Intel ceded 370bps to AMD and Arm-based hyperscaler silicon in Q1 2026 (INTC share now 54.9%) — but the cross-cohort signal is bull-case-validating for AMD; Mizuho raised AMD PT to $515 from $415 with Outperform reiterated on May 12 per 24-7 Wall St on agentic-AI server demand and AMD\'s CPU+GPU positioning, analyst Vijay Rakesh framing AMD\'s data-center inflection — Wall Street consensus PT $445.02 trails Mizuho meaningfully, JP Morgan PT $385 (May 6), Citigroup PT $358 (May 7), market cap ~$742B with P/E ~152x; Daily Political flagged Friday that an AMD EVP sold $10.83M of stock — the proximate insider-sale overhang as the cohort sells off; the May 5 Q1 blowout still sets the bar into NVDA\'s May 20 AMC print — AMD reported EPS $1.37 vs $1.29 consensus and revenue $10.25B (+38% YoY) vs $9.92B estimate per CNBC / Yahoo Finance / TradingKey, Data Center hitting $5.8B (+57% YoY) with CEO Lisa Su flagging Data Center as AMD\'s "main growth engine" driven by EPYC server CPUs and Instinct GPUs, AMD raised Q2 revenue guide to $11.2B and the stock soared 20%+ the day after pushing market cap past $690B; CSCO +17% Thursday close on Q3 AI-infrastructure orders forecast raised to $9B from $5B annual on $5.3B YTD bookings per CNBC / Motley Fool / 24-7 Wall St — six firms hiked CSCO PTs, biggest single-day rally since 2002 dot-com unwind, hyperscaler-pull signal directly supportive of AMD Instinct / NVDA H200/H100/B200 order books; UBS raised NVDA PT to $275 from $245 Friday per Tim Arcuri framing "set-up for a good set of numbers," Wells Fargo separately at $315 per GuruFocus, NVDA consensus PT $258 with 41 Strong Buys; cumulative $725B FY26 hyperscaler capex envelope per FT compilation, Trump-Xi Beijing summit wrap Friday with NVDA H200 China license-grant overnight and Taiwan arms ruling deferred, April PPI +1.4% MoM / +6.0% YoY and Warsh confirmed 54-45 the macro frame, U Michigan May prelim 48.2 record-low sentiment', category: 'company', related: 'AMD' },
  { headline: 'Meta (META) still digesting the April 29 Q1 release that BUMPED 2026 capex guide to $125B-$145B (up from $115B-$135B prior) — Zuckerberg citing higher component pricing "particularly memory" and additional data center costs per Fortune / Yahoo Finance / Tom\'s Hardware, the $135B midpoint nearly DOUBLE 2025\'s $72B spend (+61.7% YoY) and consuming an estimated 70% of world\'s memory output, plus land/power/skilled labor for AI data centers — stock had tumbled 6%+ after-hours on the original Q1 print despite a beat (rev $56.31B vs $55.45B est, adj EPS $7.31 vs $6.79 est, fastest revenue growth since 2021 at +33% YoY, operating margin holding at 41%, Zuckerberg flagging "significantly upgraded" Meta AI from the Superintelligence lab); Tom\'s Hardware separately reporting Meta is CUTTING ~8,000 jobs to fund AI infrastructure, Zuckerberg signaling 2026 infra spend will exceed all of 2024 + 2025 combined; the $145B-high-end pulls Meta to the top of the $725B FY26 cumulative four-hyperscaler envelope per FT (AMZN $200B / GOOGL $180-190B / META $125-145B / MSFT $190B, +77% YoY from last year\'s $410B record) — AI-spend ROI question NEWLY SHARPENED by Fortune\'s flag that "half of Google\'s and Amazon\'s blowout AI profits came from a stake in Anthropic," but CSCO +17% Thursday close on AI-infrastructure order forecast raised from $5B to $9B annual on $5.3B YTD bookings per CNBC / Motley Fool / 24-7 Wall St demonstrating the hyperscaler-pull conviction (order-book demand FROM the META capex spend) is structurally intact; Meta\'s Dina Powell McCormick was part of the Trump 16-CEO Beijing delegation, the Trump-Xi summit wrapped Friday with Bessent confirming the bilateral "Board of Trade" framework, 200 Boeing 737 confirmed order (vs ~500 modeled, BA -4% Thursday), Xi pledging Beijing won\'t send weapons to Iran per CNBC summit takeaways but Taiwan arms ruling deferred and no rare-earths deal in the May add-on; NVDA H200 export-license grant to ~10 Chinese firms overnight per CNBC reshaping the AI-cohort tape ahead of NVDA\'s May 20 AMC, UBS raised NVDA PT to $275 from $245 Friday, S&P 500 futures -1.2% / Nasdaq-100 -1.6% pre-market the risk-off open, April PPI +1.4% MoM / +6.0% YoY and Warsh confirmed 54-45 the macro frame', category: 'company', related: 'META' },
  { headline: 'Strategy (MSTR) closed Thursday May 14 +6.6% on the CLARITY Act 15-9 Senate Banking advance per CryptoTimes — the company\'s 818,869-BTC position back at issue Friday morning as BTC slipped to $80,326.56 on the Crypto.com tape (-0.69% 24h) after Thursday\'s reclaim of $81K, the May 11 buy of 535 BTC at $80,340 (total $43M, funded via $0.1M STRC ATM + $42.9M MSTR ATM) now near flat, company-wide average cost basis $75,540 across MSTR + STRC with total cost $61.86B and BTC Yield YTD 9.4% per Bitcoin.com News; Saylor told Bitcoin Magazine via podcast "Even if we sell 1 bitcoin, we will buy 10 to 20 more" — explicit net-accumulation stance maintained after the Q1 call had floated possible BTC sales to fund the perpetual-preferred dividend stack (STRC, STRK/STRF/STRD totaling $1.5B annual), Saylor having previously framed BTC-sales-to-fund-dividends as "inconsequential / a big nothing-burger" on the model "buy 10 Bitcoin, sell one to fund dividends, buy 10 more, sell one more" with proceeds earmarked to retire $8.2B in convertible debt or buy MSTR when mNAV <1.22x; Q1 already booked a $12.54B unrealized loss under FASB fair-value rules generating a $2.2B deferred-tax asset to offset future gains; Wednesday May 13\'s structural -$635M US spot BTC ETF outflow led by IBIT -$284.69M per CoinGlass / 24-7 Wall St had been the institutional-de-risking signal that drove the sub-$80K break to $78,738 weekly-low, the Thursday reclaim of $81K materially powered by the Senate Banking 15-9 CLARITY Act bipartisan advance per CoinDesk / CNBC — Coinbase +10% close $216.01 / three-month high on the same catalyst, XRP +4.49% best major; full Senate floor needs 60-vote cloture with Memorial Day May 21 recess deadline, White House targeting July 4 signing; Schwab launched spot BTC/ETH retail trading May 13 at 75bps with Paxos execution per CoinDesk introducing legacy-brokerage distribution that materially expands non-exchange BTC demand long-term; Trump-Xi Beijing summit wrap Friday with cordial language but Taiwan ruling deferred / no rare-earths deal, April PPI +1.4% MoM / +6.0% YoY and Warsh confirmed 54-45 the macro overhang, U Michigan May prelim 48.2 record-low sentiment', category: 'company', related: 'MSTR' },
  { headline: 'Bitcoin trading $80,326.56 Friday May 15 13:00 UTC on the Crypto.com tape (+0.69% 24h, range $79,552.04-$82,065.42, 24h volume value ~$452.2M) — slipped back below $81K after Thursday\'s CLARITY-Act-driven reclaim, Friday pre-market action saw BTC open $81,069.54 (+2.3% vs Thurs open) and drift down to $80,596 by 7:10am ET per Yahoo Finance with Blockchain Reporter pegging the level at $80,832 "as Powell exits and Warsh takes over the pattern everyone is watching"; the post-Thursday softening coming AGAINST the Senate Banking CLARITY Act 15-9 BIPARTISAN advance to the full Senate floor per CoinDesk / CNBC / TheStreet Crypto (Dem cross-overs Sens. Gallego and Alsobrooks) — bill writes statutory digital-commodity classification for BTC and creates a CFTC-primary regulatory regime, full Senate floor needs 60-vote cloture with Memorial Day recess May 21 the proximate deadline and White House targeting July 4, 2026 for signing; structurally Wednesday May 13\'s -$635M US spot BTC ETF outflow (3-month high per CoinGlass / 24-7 Wall St, IBIT alone -$284.69M) remains the de-risk overhang with total spot BTC ETF AUM still $105.01B and IBIT >$66B AUM / ~810K-BTC holdings; the macro backdrop intact — April PPI +1.4% MoM / +6.0% YoY Wednesday (biggest YoY since Dec 2022, gas +15.6% MoM) and Warsh confirmed 54-45 Wednesday evening with Wall Street post-PPI pricing zero 2026 cuts and ~39% rate-HIKE odds per CNBC / Polymarket, Warsh chairing June 16-17 FOMC, 10Y Treasury yield ~4.54% near July-2025 high and DXY at 2-week high; Strategy\'s confirmed May 11 535-BTC / $43M buy at $80,340 (818,869-BTC total, 9.4% BTC Yield YTD, $75,540 avg cost) now near flat with Saylor explicit net-accumulation stance ("Even if we sell 1 bitcoin, we will buy 10 to 20 more"); Charles Schwab launched spot BTC/ETH retail trading Wednesday May 13 at 75bps with Paxos execution per CoinDesk introducing legacy-brokerage distribution against $11.77T AUM, analyst-modeled 1% retail allocation = >$100B new spot capital over 12 months; Trump-Xi Beijing summit wrap Friday with cordial language but only 200 Boeing jets (vs ~500), Taiwan arms ruling deferred per CNBC / Axios, S&P 500 futures -1.2% / Nasdaq-100 -1.6% pre-market the risk-off cross-asset tell, Russia-Ukraine overnight Kyiv strikes killing 24+ the geopolitical overlay', category: 'crypto', related: 'BTC' },
  { headline: 'Ether trading $2,251.86 Friday May 15 13:00 UTC on the Crypto.com tape (-0.43% 24h, range $2,238.17-$2,319.62, 24h volume value ~$116.6M) — fourth performer among the four majors with the cohort flipping mixed: BTC +0.69% / XRP +0.68% / ETH -0.43% / SOL -0.68%, the Friday morning softening unwinding part of Thursday\'s Senate Banking CLARITY Act 15-9 BIPARTISAN advance bid per CoinDesk / CNBC / TheStreet Crypto (Dem cross-overs Sens. Gallego and Alsobrooks); structurally US spot ETH ETFs saw -$36.3M NET OUTFLOW Thursday May 14 per Coinfomania / Block flow trackers led by BlackRock ETHA selling ~$22.3M — the institutional selling pressure flag reversing earlier May ETHA inflows ($49.1M on May 1, $54.8M on May 4) with ETHA cumulative historical net inflow at $11.97B since launch and global spot ETH ETFs at $14B 2026 cumulative inflows per blockchain.news, Wells Fargo separately disclosed a +63.5% increase in ETHA holdings during Q1 (672,600 shares → ~1.1M shares per blockchainreporter); Charles Schwab launched spot BTC AND ETH retail trading Wednesday May 13 (75bps with Paxos execution per CoinDesk) bringing one of the largest traditional brokerages directly into crypto distribution against $11.77T AUM with Schwab clients already holding ~20% of all assets in US spot crypto ETPs per Investor Ideas, Morgan Stanley preparing comparable E*Trade spot-crypto launch — legacy-brokerage on-ramp framework structurally bullish for ETH ETP flows long-term but pressuring spot-exchange fee economics short-term; the CLARITY Act now to the full Senate floor needing 60-vote cloture with Memorial Day recess May 21 the proximate deadline and White House targeting July 4 signing; April PPI +1.4% MoM / +6.0% YoY and Warsh confirmed 54-45 Wednesday evening with Wall Street pricing zero 2026 cuts and ~39% rate-HIKE odds per CNBC keeping the macro overhang, 10Y Treasury yield ~4.54% near July-2025 high and DXY at 2-week high, U Michigan May prelim 48.2 record-low sentiment; Trump-Xi Beijing summit wrap Friday with cordial language but Taiwan arms ruling deferred ("I will make a determination") per CNBC / Axios, S&P 500 futures -1.2% / Nasdaq-100 -1.6% the risk-off cross-asset tape, Russia-Ukraine overnight Kyiv strikes killing 24+ (incl. 3 children) the geopolitical overlay', category: 'crypto', related: 'ETH' },
  { headline: 'Solana trading $90.60 Friday May 15 13:00 UTC on the Crypto.com tape (-0.68% 24h, range $90.27-$93.68, 24h volume value ~$14.1M) — slipped back below the $93 descending-resistance trendline that had capped upside since early March per CoinPedia, the WEAKEST performer among the four majors on the Friday session as the cohort flipped mixed (BTC +0.69% / XRP +0.68% / ETH -0.43% / SOL -0.68%), SOL had been recovering toward $96 mid-week on best-week-of-2026 +13% but Friday\'s profit-take reversing the gain; structurally the Alpenglow consensus upgrade is LIVE on a community test cluster as of May 11 per CoinDesk with co-founder Yakovenko projecting MAINNET rollout in Q3 2026 — the upgrade reducing transaction finality from ~12s to ~150ms (near-100x improvement) per CoinMarketCap, the structural finality catalyst stacking with Visa-and-Meta-Solana-payments expansion, Solana Swiss Research Institute launch, April 28 quantum-resistant signature migration, and Israel CMA BILS approval (1:1 ILS-pegged stablecoin on Solana with sub-400ms settlement, EY-audited reserves, Fireblocks custody); US spot Solana ETFs pulled in ~$33M weekly net inflows in early May with a single-day $56.6M institutional inflow on May 10 per Phemex / blockchain.news, combined SOL spot ETF holdings now approaching ~2% of circulating supply per CoinDesk, Futures OI surged $1.5B in May — but monthly inflows have declined six straight months (November 2025 ATH $419.38M → April 2026 $39.93M, weakest print since October 2025 launch); Senate Banking CLARITY Act 15-9 BIPARTISAN advance to the full Senate floor per CoinDesk / CNBC the Thursday-session catalyst, Wednesday\'s -$635M BTC ETF outflow (IBIT -$284.69M, 3-month high) per CoinGlass having been the cross-cohort de-risk signal; April PPI +1.4% MoM / +6.0% YoY and Warsh confirmed 54-45 the macro overlay, Trump-Xi Beijing summit wrap Friday with cordial language but Taiwan arms ruling deferred / no rare-earths deal in May add-on per CNBC / Axios, S&P 500 futures -1.2% / Nasdaq-100 -1.6% the risk-off cross-asset tape, U Michigan May prelim 48.2 record-low sentiment, Russia-Ukraine overnight Kyiv strikes killing 24+ the geopolitical overlay', category: 'crypto', related: 'SOL' },
  { headline: 'XRP trading $1.4583 Friday May 15 13:00 UTC on the Crypto.com tape (+0.68% 24h, range $1.4389-$1.5498, 24h volume value ~$23.8M) — held the bid as one of two majors green on the session (BTC +0.69% / XRP +0.68% / ETH -0.43% / SOL -0.68%) after Thursday\'s +4.49% best-major rally on the Senate Banking Committee CLARITY Act 15-9 BIPARTISAN advance to the full Senate floor per CoinDesk / CNBC / TheStreet Crypto / 24-7 Wall St — the bill permanently classifies XRP as a digital commodity (the SEC and CFTC having jointly classified XRP a digital commodity in March 2026 but the CLARITY Act writes it into statute removing the 2020 SEC-Ripple enforcement overhang once and for all), 24-7 Wall St placing committee-pass scenario at $1.65-$1.80 short-term climbing to $3-$5 by year-end with full Senate passage + ETF launches; structurally the US spot XRP ETF complex now has 7 funds LIVE (Bitwise XRP, Canary XRPC, Franklin Templeton XRPZ, Grayscale GXRP, REX-Osprey XRPR, 21Shares TOXR, Bitwise 10 BITW) with combined ~$1B AUM holding 847.9M XRP — single-day inflow $25.8M on May 11 the biggest since January, cumulative $1.35B inflows per XRP-Insights, weekly inflows running ~$34.2M per MEXC, on-chain whale wallet count hitting all-time high 332,230 wallets holding 10,000+ XRP per BanklessTimes; the committee 15-9 final tally now structurally important for the 60-vote cloture math on the full Senate floor (7+ Democrats must cross, Dem cross-overs in committee Sens. Gallego and Alsobrooks) with Memorial Day recess May 21 the proximate legislative deadline beyond which Sen. Lummis had warned the bill could push to 2030, White House targeting July 4, 2026 signing; Coinbase +10% close $216.01 / three-month high on the same catalyst per CryptoTimes, BTC slipped to $80,326.56 Friday after reclaiming $81K Thursday, Strategy +6.6% Thursday; Trump-Xi Beijing summit wrap Friday with cordial language but Taiwan ruling deferred per CNBC / Axios, April PPI +1.4% MoM / +6.0% YoY and Warsh confirmed 54-45 the macro frame, S&P 500 futures -1.2% / Nasdaq-100 -1.6% pre-market risk-off, Russia-Ukraine overnight Kyiv strikes killing 24+ the geopolitical overlay', category: 'crypto', related: 'XRP' },
  { headline: 'US spot Bitcoin ETFs posted a structural -$635M SINGLE-DAY OUTFLOW Wednesday May 13 — the LARGEST single-day BTC ETF outflow in 3 months per CoinGlass / 24-7 Wall St / Crypto Times / Blockchain Reporter — led by BlackRock\'s iShares Bitcoin Trust IBIT shedding -$284.69M, with Fidelity\'s FBTC and Ark\'s ARKB contributing elevated double-digit exits and the remaining ~$350M spread across the rest of the field; the reversal materially sharper than the May 7 -$268.5M print that had snapped the prior six-week / $3.4B-cumulative inflow streak, total spot BTC ETF AUM still $105.01B following the May 13 session — IBIT remains the largest spot BTC ETF (>$66B AUM, ~810K-BTC holdings, larger by AUM than most of BlackRock\'s gold and EM ETFs combined), cumulative net inflow since launch dropped from $59.76B to $58.5B in 5 sessions; the de-risk move drove the BTC tape under $80K Wednesday to $78,738 weekly-low — Thursday May 14 saw structural reclaim of the $81K handle on the Senate Banking CLARITY Act 15-9 BIPARTISAN advance to the full Senate floor per CoinDesk / CNBC (Dem cross-overs Sens. Gallego and Alsobrooks) — but the Friday May 15 13:00 UTC tape has BTC back at $80,326.56 (-0.69% 24h on Crypto.com), the CLARITY catalyst partially fading as Wall Street pre-market positioning tilts risk-off (S&P 500 futures -1.2% / Nasdaq-100 -1.6% per CNBC / ts2.tech); structural drivers — hot April PPI +1.4% MoM / +6.0% YoY (biggest YoY since Dec 2022, gas +15.6%) and Warsh confirmed 54-45 Wednesday evening (closest-margin confirmation in modern era, only Sen. Fetterman crossing) vowing "strictly independent" monetary policy even as Trump publicly pressed for cuts, Warsh now set to chair the June 16-17 FOMC, Wall Street post-PPI pricing zero 2026 cuts with ~39% rate-HIKE odds per CNBC / Polymarket, 10Y Treasury yield ~4.54% near July-2025 high and DXY at 2-week high; Charles Schwab\'s spot BTC/ETH retail-trading launch May 13 (Wednesday) at industry-low 75bps with Paxos execution per CoinDesk bringing legacy-brokerage distribution directly into the crypto rails (Schwab clients already ~20% of all US spot crypto ETP assets per Investor Ideas) the structural Coinbase-fee-moat pressure, Strategy\'s May 11 535-BTC / $43M buy at $80,340 (818,869-BTC total at $75,540 avg) reasserting treasury demand; Trump-Xi Beijing summit wrap Friday with cordial language but Taiwan ruling deferred per CNBC / Axios', category: 'crypto', related: 'BTC' },
  { headline: 'Russia hammered Kyiv overnight Thursday-Friday May 14-15 in what has become the LARGEST AERIAL ASSAULT in a two-day window since the war began — cumulative attacks across May 13 and May 14 totaling 1,567 drones plus 56 missiles (drone intercept rate 94%, missile intercept rate only 7%) per CNN / NPR / Kyiv Independent / CBS News, the death toll from the Darnytskyi apartment building strike now AT LEAST 24 KILLED INCLUDING 3 CHILDREN (one age 12) with 48+ injured, an apartment block in central Kyiv flattened and damage reported across six city districts; the Friday escalation extends the pattern that began after the Trump-brokered three-day Victory Day ceasefire (May 9-11, 1,000-for-1,000 prisoner exchange) formally expired Monday evening — Russia hit Kyiv overnight Tuesday May 12 with 200+ drones, May 13 layered a daytime 800+ drone wave hitting civilian infrastructure including a kindergarten in Obolon district, and the Thursday-Friday tape now represents the de-facto WORST single-period escalation since 2024, Ukrainian President Volodymyr Zelensky directing his military to prepare "possible formats for our response" per Kyiv Independent; Ukrainian Foreign Minister Andrii Sybiha reiterating Kyiv had proposed extending the truce but Moscow instead escalated — Trump still publicly claiming a "deal soon" framing as apartment blocks flatten, Putin\'s earlier "war is coming to an end" framing now visibly stale; the Institute for the Study of War concluded "ceasefires without explicit enforcement mechanisms, credible monitoring, and defined dispute resolution processes are unlikely to hold," the de-facto collapse stacks on top of the fraying US-Iran 14-point MoU (May 14 letter from 52 senators + 177 congressmen to Trump rejecting any deal allowing Iran continued uranium enrichment per Axios / Wikipedia, Iran threatening weapons-grade enrichment as talks falter per Euronews) and runs into the Trump-Xi Beijing summit wrap where Xi explicitly pledged Beijing will not send weapons to Iran (ruling out surface-to-air missile transfers) per CNBC summit takeaways; Russia-Ukraine ceasefire collapse extending while Israel-Lebanon Round 3 Washington talks running through Friday May 15 (April 17 ceasefire formally expires Sunday May 17) the parallel multi-front diplomatic frame, WTI ~$108 / Brent ~$108-109 on Hormuz-stays-closed plus Iran-war fuel pass-through the macro pricing impact', category: 'general', related: '' },
  { headline: 'Round 3 of direct Lebanon-Israel talks running through Friday May 15 at the US State Department after sessions opened Thursday May 14 per NBC News / The National / Euronews / Al Jazeera / France24 — Lebanon\'s delegation pressing for a FULL ceasefire FIRST, then Israeli withdrawal from occupied southern Lebanese territory, THEN political Hezbollah disarmament, the sequencing point a fundamental ask versus Israeli position that disarmament precedes withdrawal; the talks taking place under the urgent backdrop that the APRIL 17 CEASEFIRE FORMALLY EXPIRES SUNDAY MAY 17 (~48 hours away), Israeli strikes have killed MORE THAN 380 PEOPLE in Lebanon since the April 17 ceasefire took effect per AFP tally of Health Ministry figures, with Wednesday May 13 strikes alone killing at least 13-15 (8 in coordinated coastal-highway raids 20-30km south of Beirut, including 2 children per Al Jazeera / Washington Post / Times of Israel), Hezbollah strongly opposed to the Washington negotiations and reportedly preparing parallel kinetic response options per France24 noting Israeli troops targeted in north Israel drone strike (Hezbollah claim) May 14; the Lebanon track runs alongside the US-Iran enrichment-moratorium MoU framework now openly fraying with the May 14 letter from 52 senators + 177 congressmen to Trump rejecting any deal allowing Iran continued enrichment per Axios / Wikipedia 2025-26 Iran-US negotiations, Iran threatening weapons-grade enrichment as talks falter per Euronews — the one-page Witkoff-Kushner memo would have Iran suspend uranium enrichment and potentially turn over >900 lbs (408kg) enriched uranium with the moratorium duration in active negotiation at 12-15 years; Friday\'s Washington Lebanon-Israel talks overlap directly with Trump-Xi Beijing summit wrap where Xi explicitly pledged Beijing will not send weapons to Iran (ruling out surface-to-air missile transfers) per CNBC summit takeaways, plus the Russia-Ukraine ceasefire collapse with 24+ killed in overnight Kyiv strikes including 3 children — the same-day multi-front diplomatic frame; oil tape bid with WTI ~$108 / Brent ~$108-109 on the Trump-Xi joint Hormuz-must-remain-open agreement plus Xi commitment to buy more US oil per CNBC / ts2.tech, Pentagon pegs total Iran-war cost at $29B per CNN', category: 'general', related: '' },
  { headline: 'Oil tape bid Friday May 15 with WTI ~$108/bbl and Brent ~$108-109/bbl per ts2.tech holding above Thursday\'s $101 WTI / $105 Brent levels — the cross-asset overlay of the Trump-Xi Beijing summit wrap Friday delivering the joint Hormuz-must-remain-open agreement AND Xi "expressed interest" in buying more American crude to reduce China dependence on the strait per CNBC\'s "three big takeaways," but Hormuz still effectively CLOSED with EIA reporting crude oil and fuel flows through the Strait declined by ~4 MILLION BPD in March-April since the US-Israel war started Feb 28, Saudi Aramco CEO Amin Nasser\'s prior warning that the oil market will NOT normalize until 2027 if Hormuz disruption persists past mid-June still the structural overhang per Al Jazeera; Aramco continues to run its east-west Petroline bypass at 7M barrels per day transporting crude from the Gulf coast to the Red Sea, total Iran-war net oil supply loss now ~880 million barrels with the market losing ~100M barrels per WEEK that Hormuz stays closed per CNBC / Eastern Herald / Foreign Policy Journal, Polymarket placing 51.5% probability on WTI hitting $110 before end-May 2026 per Foreign Policy Journal, IEA warning global oil market likely to remain heavily undersupplied through October even if conflict ends next month; Pentagon pegs total Iran-war cost at $29B per CNN, Tehran framed the US 14-point MoU negotiated by Witkoff and Kushner as amounting to "surrender" with the ongoing MoU framework on a 12-15 year moratorium on uranium enrichment per Axios now under bipartisan-congressional fire — May 14 letter from 52 senators + 177 congressmen rejecting any deal allowing continued enrichment, Iran threatening weapons-grade enrichment as talks falter per Euronews; the Trump-Xi Beijing summit wrap also delivered Bessent "Board of Trade" framework AND 200 Boeing 737 jet order (vs ~500 expectation, BA -4% Thursday) AND ≥$10B/year Chinese ag purchases per USTR Greer — but Taiwan arms ruling deferred ("I will make a determination") and no rare-earths or tariff deal in the May add-on; S&P 500 futures -1.2% / Nasdaq-100 -1.6% the risk-off pre-market reaction per CNBC / ts2.tech, 10Y Treasury yield ~4.54% near July-2025 high, U Michigan May prelim 48.2 record-low sentiment with ~33% citing gas prices, April Retail Sales gas stations +2.8% MoM the consumer-side fuel pass-through tell', category: 'general', related: '' },
  { headline: 'Trump and Xi wrapped the Beijing summit Friday May 15 with cordial language reading "few clear wins" per CNBC\'s "three big takeaways" / Washington Times / Axios / IBTimes / NBC News — concrete commitments deliverable mix: China committed to 200 Boeing 737 MAX jets (vs ~500 Wall Street expectation, BA -4% Thursday afternoon per CNBC / USNews / Bloomberg, the 200-jet final deal representing ~3% of BA\'s ~6,719-aircraft end-March 2026 backlog with NO details released on jet types or delivery timelines per BiggoNews), US expecting ≥$10 BILLION/YEAR in Chinese agricultural purchases per USTR Greer, a bilateral "Board of Trade" framework to manage non-sensitive investment per Treasury Secretary Bessent, Xi "expressed interest" in buying more US oil and the joint language that the Strait of Hormuz "must remain open to support the free flow of energy" — plus plans for another meeting this fall and a previously-announced October-Busan-deal-extension on fentanyl precursors (Oct 2025 cut tariffs 20%→10% bringing total China duties 57%→47%); NOTABLE UNRESOLVED — Trump said "I will make a determination" on the Taiwan arms sale question (no formal answer), Iran got no firm Chinese commitment despite the Hormuz language, no tariff cuts and NO RARE-EARTHS DEAL in the May summit add-on; the 16-CEO delegation included Apple\'s Tim Cook (AAPL ATH-area close near $300), Tesla\'s Elon Musk (TSLA $445.13 Thursday), BlackRock\'s Larry Fink, Boeing\'s Kelly Ortberg (BA -4%), Citigroup\'s Jane Fraser, Meta\'s Dina Powell McCormick, Visa\'s Ryan McInerney AND last-minute add Nvidia\'s Jensen Huang per Bloomberg / SCMP / CNBC — overnight the US Department of Commerce APPROVED ~10 Chinese firms (Alibaba, ByteDance, Tencent, JD.com) to purchase NVDA H200 chips up to 75,000 each per CNBC, NVDA closed +4.4% $235.74 Thursday although ZERO deliveries yet under Beijing pressure on national-champion firms to vet/block; market read: disappointment vs. expectations — S&P 500 futures -1.2% / Nasdaq-100 -1.6% / Dow -440 points pre-market Friday per CNBC / ts2.tech, INTC -4% pre-market on UBS server-CPU share data, AMD -3%, 10Y Treasury yield ~4.54% near July-2025 high and DXY at 2-week high, oil bid with WTI / Brent ~$108-109 on the Hormuz language; Trump departs Beijing today, the first US-sitting-president visit to China in nine years', category: 'general', related: '' },
];

// Get date string in YYYY-MM-DD format
function getDateString(daysAgo = 0) {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  return date.toISOString().split('T')[0];
}

// Fetch company-specific news
async function fetchCompanyNews(symbol: string): Promise<any[]> {
  try {
    const to = getDateString(0);
    const from = getDateString(3); // Last 3 days
    const response = await fetch(
      `https://finnhub.io/api/v1/company-news?symbol=${symbol}&from=${from}&to=${to}&token=${FINNHUB_API_KEY}`
    );
    if (!response.ok) return [];
    const data = await response.json();
    // Take top 2 per company, tag with ticker
    return data.slice(0, 2).map((item: any) => ({
      ...item,
      related: symbol, // Ensure ticker is set
    }));
  } catch {
    return [];
  }
}

export async function GET() {
  // If no API key, return fallback immediately
  if (!process.env.FINNHUB_API_KEY) {
    return NextResponse.json({
      headlines: FALLBACK_NEWS,
      source: 'fallback',
      message: 'Set FINNHUB_API_KEY in .env.local for live news'
    });
  }

  const now = Date.now();
  if (cachedHeadlines && (now - cacheTimestamp) < CACHE_DURATION) {
    return NextResponse.json({
      headlines: cachedHeadlines,
      source: 'finnhub',
      cached: true,
    });
  }

  try {
    // Fetch general news, crypto news, and company-specific news in parallel
    const [generalResponse, cryptoResponse, ...companyNews] = await Promise.all([
      fetch(
        `https://finnhub.io/api/v1/news?category=general&token=${FINNHUB_API_KEY}`
      ),
      fetch(
        `https://finnhub.io/api/v1/news?category=crypto&token=${FINNHUB_API_KEY}`
      ),
      ...KEY_TICKERS.slice(0, 5).map(ticker => fetchCompanyNews(ticker)) // Limit to 5 to avoid rate limits
    ]);

    if (!generalResponse.ok) {
      throw new Error(`Finnhub API error: ${generalResponse.status}`);
    }

    const generalData = await generalResponse.json();
    const cryptoData = cryptoResponse.ok ? await cryptoResponse.json() : [];

    // Combine all news
    const allNews: any[] = [];

    // Add crypto news with ticker detection (using word boundaries to avoid false matches)
    const cryptoPatterns = [
      { pattern: /\b(xrp|ripple)\b/i, ticker: 'XRP' },      // Check XRP first (less common words)
      { pattern: /\b(solana|sol)\b/i, ticker: 'SOL' },       // SOL as word boundary
      { pattern: /\b(doge|dogecoin)\b/i, ticker: 'DOGE' },
      { pattern: /\b(ethereum|eth)\b/i, ticker: 'ETH' },     // ETH as word boundary
      { pattern: /\b(bitcoin|btc)\b/i, ticker: 'BTC' },      // BTC last (most common, catch-all)
    ];

    cryptoData.slice(0, 6).forEach((item: any) => {
      const headline = item.headline || '';
      // Find matching crypto ticker
      let ticker = '';
      for (const { pattern, ticker: t } of cryptoPatterns) {
        if (pattern.test(headline)) {
          ticker = t;
          break;
        }
      }

      allNews.push({
        headline: item.headline,
        category: 'crypto',
        related: ticker,
        source: item.source,
        url: item.url,
        image: item.image,
        datetime: item.datetime,
      });
    });

    // Add company news (they have tickers)
    companyNews.flat().forEach((item: any) => {
      if (item && item.headline) {
        allNews.push({
          headline: item.headline,
          category: item.category || 'company',
          related: item.related || '',
          source: item.source,
          url: item.url,
          image: item.image,
          datetime: item.datetime,
        });
      }
    });

    // Add general news
    generalData.slice(0, 10).forEach((item: any) => {
      allNews.push({
        headline: item.headline,
        category: item.category || 'general',
        related: item.related || '',
        source: item.source,
        url: item.url,
        image: item.image,
        datetime: item.datetime,
      });
    });

    // Deduplicate by headline
    const seen = new Set();
    const unique = allNews.filter(item => {
      const key = item.headline.toLowerCase().slice(0, 50);
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    });

    // Separate news with tickers from general news
    const withTickers = unique.filter(item => item.related && item.related.length > 0);
    const withoutTickers = unique.filter(item => !item.related || item.related.length === 0);

    // Sort each group by datetime
    withTickers.sort((a, b) => (b.datetime || 0) - (a.datetime || 0));
    withoutTickers.sort((a, b) => (b.datetime || 0) - (a.datetime || 0));

    // Take up to 5 ticker news + fill rest with general news (total 8)
    const sorted = [
      ...withTickers.slice(0, 5),
      ...withoutTickers.slice(0, 8 - Math.min(withTickers.length, 5))
    ];

    cachedHeadlines = sorted;
    cacheTimestamp = now;

    return NextResponse.json({
      headlines: sorted,
      source: 'finnhub',
      cached: false,
    });
  } catch (error) {
    console.error('News API error:', error);
    if (cachedHeadlines) {
      return NextResponse.json({
        headlines: cachedHeadlines,
        source: 'finnhub',
        cached: true,
        stale: true,
      });
    }
    return NextResponse.json({
      headlines: FALLBACK_NEWS,
      source: 'fallback',
      error: 'Failed to fetch live news',
    });
  }
}
