import { NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';

const FINNHUB_API_KEY = process.env.FINNHUB_API_KEY || 'demo';

// Server-side cache (5 minutes)
let cachedHeadlines: any[] | null = null;
let cacheTimestamp: number = 0;
const CACHE_DURATION = 5 * 60 * 1000;

// Key tickers to fetch company-specific news for
const KEY_TICKERS = ['NVDA', 'AAPL', 'TSLA', 'MSFT', 'META', 'AMZN', 'GOOGL', 'AMD', 'NFLX', 'COIN'];

// Fallback headlines when API fails or no key (updated 2026-07-03 13:00 UTC)
const FALLBACK_NEWS = [
  { headline: 'Friday July 3 13:00 UTC PRE-MARKET / OPENING-BELL-WINDOW tape — THURSDAY DOW-RECORD-CLOSE 52,900.07 +594.83 +1.14% / S&P-500 7,483.24 FLAT / NASDAQ 25,832.67 -0.8% SEMI-DRAG the WEAK-JUNE-PAYROLLS-REVIVE-RATE-CUT-HOPES bid into AMERICAS-250TH-BIRTHDAY-LONG-WEEKEND + FED-CHAIR-KEVIN-WARSH JULY-2-COMMENTS-EASE-INFLATION-FEARS after HOLDING-RATES-STEADY-AT-JUNE-DEBUT + SEMIS-THE-LONE-LAGGARD as HBM-MEMORY-SHORTAGE-DEEPENS (B300-NEEDS-8-HBM-CHIPS / DGX-B300 768-DRAM-DIES / RELIEF-NOT-UNTIL-LATE-2027-2028) + ARM -7%-PREMARKET CEO-RENE-HAAS-WARNS-SMARTPHONE-UNIT-GROWTH-FLIPS-NEGATIVE + OPENAI-ALTMAN-BINDING-CONSTRAINT-NOW-CHIPS AI-DATACENTERS-~70%-GLOBAL-MEMORY-2026 / DRAM-+50-55%-QoQ / STARGATE-SAMSUNG-SK-HYNIX-~900K-WAFER-STARTS-MO + CRYPTO-ETF-CAPITULATION BTC-ETFs-~$4.5B-JUNE-OUTFLOWS-WORST-MONTH / $294.62M-OUT-JULY-1 / CUMULATIVE-SINCE-MAY-6-~$8.475B + CITI-CUTS-BTC-$112K-TO-$82K / ETH-$3,175-TO-$2,240 / NET-ETF-INFLOW-TO-ZERO + CRYPTO-COHORT BTC $62,613 +1.83% / ETH $1,758 +3.53% / SOL $82.16 +1.94% / XRP $1.13 +4.35% ALL-GREEN-ON-JULY-2-WARSH-DOVISH-BID but BTC-WELL-OFF-MAY-$73K-HIGH + IRAN-2026-CEASEFIRE JUNE-17-US-IRAN-MoU-60-DAY-EXTENSION / PEACE-NUCLEAR-TALKS-PAUSED-FOR-KHAMENEI-STATE-FUNERAL + FIFA-WORLD-CUP-2026-ON-US-SOIL + US-HEAT-WAVE-POSSIBLE-HOTTEST-JULY-4TH-ON-RECORD — DOW RECORD-CLOSE 52,900.07 +1.14% per TheStreet / CNBC.', category: 'general', related: '' },
  { headline: 'Macro Friday July 3 13:00 UTC MACRO-TAPE / RATE-PATH-WATCH — THURSDAY DOW-RECORD-CLOSE 52,900.07 +594.83 +1.14% / S&P-500 7,483.24 ESSENTIALLY-FLAT / NASDAQ 25,832.67 -0.8%-SEMI-DRAG the WEAK-JUNE-NONFARM-PAYROLLS-REVIVE-RATE-CUT-HOPES bid into AMERICAS-250TH-BIRTHDAY-LONG-JULY-4-WEEKEND + FED-CHAIR-KEVIN-WARSH-JULY-2-COMMENTS-EASE-INFLATION-FEARS after HOLDING-RATES-STEADY-AT-JUNE-DEBUT / TOOK-2026-CUT-OFF-THE-TABLE + H1-2026-TECH-LED-BUT-MAG-7-SOLD-OFF-SHARPLY-LATE-JUNE + HBM-MEMORY-SHORTAGE-DEEPENS (B300-NEEDS-8-HBM-CHIPS / DGX-B300 768-DRAM-DIES / RELIEF-NOT-UNTIL-LATE-2027-2028) + ARM -7%-PREMARKET CEO-RENE-HAAS-WARNS-SMARTPHONE-UNIT-GROWTH-FLIPS-NEGATIVE + OPENAI-ALTMAN-BINDING-CONSTRAINT-NOW-CHIPS AI-DATACENTERS-~70%-GLOBAL-MEMORY-2026 / DRAM-+50-55%-QoQ / STARGATE-SAMSUNG-SK-HYNIX-~900K-WAFER-STARTS-MO-~40%-GLOBAL + CRYPTO-ETF-CAPITULATION BTC-ETFs-~$4.5B-JUNE-OUTFLOWS-WORST-MONTH-SINCE-INCEPTION / $294.62M-OUT-JULY-1 / CUMULATIVE-SINCE-MAY-6-~$8.475B + CITI-CUTS-BTC-$112K-TO-$82K / ETH-$3,175-TO-$2,240 / NET-ETF-INFLOW-ASSUMPTION-TO-ZERO + CRYPTO-COHORT BTC $62,613 +1.83% / ETH $1,758 +3.53% / SOL $82.16 +1.94% / XRP $1.13 +4.35% ALL-GREEN-ON-WARSH-DOVISH-BID but BTC-WELL-OFF-MAY-$73K-HIGH + IRAN-2026-CEASEFIRE JUNE-17-US-IRAN-MoU-60-DAY-EXTENSION / PEACE-NUCLEAR-TALKS-PAUSED-FOR-KHAMENEI-STATE-FUNERAL + VATICAN-DECLARES-SSPX-IN-SCHISM + FIFA-WORLD-CUP-2026-ON-US-SOIL + US-HEAT-WAVE-POSSIBLE-HOTTEST-JULY-4TH-ON-RECORD — DOW RECORD-CLOSE 52,900.07 +1.14% per TheStreet / CNBC.', category: 'general', related: '' },
  { headline: 'Friday July 3 13:00 UTC NVDA-FOCUS-TAPE / SEMI-DESK-WATCH — NVDA-+~7.3%-H1-LEADER-BUT-SEMIS-THE-LONE-JUL-2-LAGGARD dragged NASDAQ 25,832.67 -0.8% even as THURSDAY DOW-RECORD-CLOSE 52,900.07 +594.83 +1.14% / S&P-500 7,483.24 FLAT the WEAK-JUNE-PAYROLLS-REVIVE-RATE-CUT-HOPES bid into AMERICAS-250TH-BIRTHDAY-LONG-WEEKEND + NVDA-HBM-DEMAND-VS-SUPPLY-CRUNCH-FRONT-AND-CENTER as HBM-MEMORY-SHORTAGE-DEEPENS (B300-NEEDS-8-HBM-CHIPS / DGX-B300 768-DRAM-DIES / RELIEF-NOT-UNTIL-LATE-2027-2028) + FED-CHAIR-KEVIN-WARSH-JULY-2-COMMENTS-EASE-INFLATION-FEARS after HOLDING-RATES-STEADY-AT-JUNE-DEBUT / TOOK-2026-CUT-OFF-THE-TABLE + ARM -7%-PREMARKET CEO-RENE-HAAS-WARNS-SMARTPHONE-UNIT-GROWTH-FLIPS-NEGATIVE + OPENAI-ALTMAN-BINDING-CONSTRAINT-NOW-CHIPS AI-DATACENTERS-~70%-GLOBAL-MEMORY-2026 / DRAM-+50-55%-QoQ / STARGATE-SAMSUNG-SK-HYNIX-~900K-WAFER-STARTS-MO-~40%-GLOBAL + CRYPTO-ETF-CAPITULATION BTC-ETFs-~$4.5B-JUNE-OUTFLOWS-WORST-MONTH / $294.62M-OUT-JULY-1 / CUMULATIVE-SINCE-MAY-6-~$8.475B + CITI-CUTS-BTC-$112K-TO-$82K / ETH-$3,175-TO-$2,240 / NET-ETF-INFLOW-TO-ZERO + CRYPTO-COHORT BTC $62,613 +1.83% / ETH $1,758 +3.53% / SOL $82.16 +1.94% / XRP $1.13 +4.35% ALL-GREEN-ON-WARSH-DOVISH-BID but BTC-WELL-OFF-MAY-$73K-HIGH + IRAN-2026-CEASEFIRE JUNE-17-US-IRAN-MoU-60-DAY-EXTENSION / PEACE-NUCLEAR-TALKS-PAUSED-FOR-KHAMENEI-STATE-FUNERAL + FIFA-WORLD-CUP-2026-ON-US-SOIL + US-HEAT-WAVE-POSSIBLE-HOTTEST-JULY-4TH-ON-RECORD — DOW RECORD-CLOSE 52,900.07 +1.14% per TheStreet / CNBC.', category: 'general', related: 'NVDA' },
  { headline: 'Friday July 3 13:00 UTC AAPL-FOCUS-TAPE / MEGACAP-WATCH — AAPL-RECENT-EARNINGS-BEAT-AMID-MEMORY-CRUNCH with MUSK-VS-ALTMAN-FEUD-IN-THE-BACKDROP as THURSDAY DOW-RECORD-CLOSE 52,900.07 +594.83 +1.14% / S&P-500 7,483.24 FLAT / NASDAQ 25,832.67 -0.8%-SEMI-DRAG the WEAK-JUNE-PAYROLLS-REVIVE-RATE-CUT-HOPES bid into AMERICAS-250TH-BIRTHDAY-LONG-WEEKEND + AAPL-SUPPLY-CHAIN-EXPOSED-TO HBM-MEMORY-SHORTAGE-DEEPENS (B300-NEEDS-8-HBM-CHIPS / DGX-B300 768-DRAM-DIES / RELIEF-NOT-UNTIL-LATE-2027-2028) + FED-CHAIR-KEVIN-WARSH-JULY-2-COMMENTS-EASE-INFLATION-FEARS after HOLDING-RATES-STEADY-AT-JUNE-DEBUT / TOOK-2026-CUT-OFF-THE-TABLE + ARM -7%-PREMARKET CEO-RENE-HAAS-WARNS-SMARTPHONE-UNIT-GROWTH-FLIPS-NEGATIVE + OPENAI-ALTMAN-BINDING-CONSTRAINT-NOW-CHIPS AI-DATACENTERS-~70%-GLOBAL-MEMORY-2026 / DRAM-+50-55%-QoQ / STARGATE-SAMSUNG-SK-HYNIX-~900K-WAFER-STARTS-MO-~40%-GLOBAL + CRYPTO-ETF-CAPITULATION BTC-ETFs-~$4.5B-JUNE-OUTFLOWS-WORST-MONTH / $294.62M-OUT-JULY-1 / CUMULATIVE-SINCE-MAY-6-~$8.475B + CITI-CUTS-BTC-$112K-TO-$82K / ETH-$3,175-TO-$2,240 / NET-ETF-INFLOW-TO-ZERO + CRYPTO-COHORT BTC $62,613 +1.83% / ETH $1,758 +3.53% / SOL $82.16 +1.94% / XRP $1.13 +4.35% ALL-GREEN-ON-WARSH-DOVISH-BID but BTC-WELL-OFF-MAY-$73K-HIGH + IRAN-2026-CEASEFIRE JUNE-17-US-IRAN-MoU-60-DAY-EXTENSION / PEACE-NUCLEAR-TALKS-PAUSED-FOR-KHAMENEI-STATE-FUNERAL + FIFA-WORLD-CUP-2026-ON-US-SOIL + US-HEAT-WAVE-POSSIBLE-HOTTEST-JULY-4TH-ON-RECORD — DOW RECORD-CLOSE 52,900.07 +1.14% per TheStreet / CNBC.', category: 'general', related: 'AAPL' },
  { headline: 'Friday July 3 13:00 UTC INTC-FOCUS-TAPE / FOUNDRY-DESK-WATCH — INTC-IN-THE-CHIP-COHORT-CROSSHAIRS on FOUNDRY-AND-MEMORY-SHORTAGE-FRAMING as SEMIS-THE-LONE-JUL-2-LAGGARD dragged NASDAQ 25,832.67 -0.8% while THURSDAY DOW-RECORD-CLOSE 52,900.07 +594.83 +1.14% / S&P-500 7,483.24 FLAT the WEAK-JUNE-PAYROLLS-REVIVE-RATE-CUT-HOPES bid into AMERICAS-250TH-BIRTHDAY-LONG-WEEKEND + HBM-MEMORY-SHORTAGE-DEEPENS (B300-NEEDS-8-HBM-CHIPS / DGX-B300 768-DRAM-DIES / RELIEF-NOT-UNTIL-LATE-2027-2028) + FED-CHAIR-KEVIN-WARSH-JULY-2-COMMENTS-EASE-INFLATION-FEARS after HOLDING-RATES-STEADY-AT-JUNE-DEBUT / TOOK-2026-CUT-OFF-THE-TABLE + ARM -7%-PREMARKET CEO-RENE-HAAS-WARNS-SMARTPHONE-UNIT-GROWTH-FLIPS-NEGATIVE + OPENAI-ALTMAN-BINDING-CONSTRAINT-NOW-CHIPS AI-DATACENTERS-~70%-GLOBAL-MEMORY-2026 / DRAM-+50-55%-QoQ / STARGATE-SAMSUNG-SK-HYNIX-~900K-WAFER-STARTS-MO-~40%-GLOBAL + CRYPTO-ETF-CAPITULATION BTC-ETFs-~$4.5B-JUNE-OUTFLOWS-WORST-MONTH / $294.62M-OUT-JULY-1 / CUMULATIVE-SINCE-MAY-6-~$8.475B + CITI-CUTS-BTC-$112K-TO-$82K / ETH-$3,175-TO-$2,240 / NET-ETF-INFLOW-TO-ZERO + CRYPTO-COHORT BTC $62,613 +1.83% / ETH $1,758 +3.53% / SOL $82.16 +1.94% / XRP $1.13 +4.35% ALL-GREEN-ON-WARSH-DOVISH-BID but BTC-WELL-OFF-MAY-$73K-HIGH + IRAN-2026-CEASEFIRE JUNE-17-US-IRAN-MoU-60-DAY-EXTENSION / PEACE-NUCLEAR-TALKS-PAUSED-FOR-KHAMENEI-STATE-FUNERAL + FIFA-WORLD-CUP-2026-ON-US-SOIL + US-HEAT-WAVE-POSSIBLE-HOTTEST-JULY-4TH-ON-RECORD — DOW RECORD-CLOSE 52,900.07 +1.14% per TheStreet / CNBC.', category: 'general', related: 'INTC' },
  { headline: 'Friday July 3 13:00 UTC TSLA-FOCUS-TAPE / MEGACAP-MOMENTUM-WATCH — TSLA-UP-~32,000%-SINCE-IPO the long-run megacap standout as THURSDAY DOW-RECORD-CLOSE 52,900.07 +594.83 +1.14% / S&P-500 7,483.24 FLAT / NASDAQ 25,832.67 -0.8%-SEMI-DRAG the WEAK-JUNE-PAYROLLS-REVIVE-RATE-CUT-HOPES bid into AMERICAS-250TH-BIRTHDAY-LONG-WEEKEND + H1-2026-TECH-LED-BUT-MAG-7-SOLD-OFF-SHARPLY-LATE-JUNE + HBM-MEMORY-SHORTAGE-DEEPENS (B300-NEEDS-8-HBM-CHIPS / DGX-B300 768-DRAM-DIES / RELIEF-NOT-UNTIL-LATE-2027-2028) + FED-CHAIR-KEVIN-WARSH-JULY-2-COMMENTS-EASE-INFLATION-FEARS after HOLDING-RATES-STEADY-AT-JUNE-DEBUT / TOOK-2026-CUT-OFF-THE-TABLE + ARM -7%-PREMARKET CEO-RENE-HAAS-WARNS-SMARTPHONE-UNIT-GROWTH-FLIPS-NEGATIVE + OPENAI-ALTMAN-BINDING-CONSTRAINT-NOW-CHIPS AI-DATACENTERS-~70%-GLOBAL-MEMORY-2026 / DRAM-+50-55%-QoQ / STARGATE-SAMSUNG-SK-HYNIX-~900K-WAFER-STARTS-MO-~40%-GLOBAL + CRYPTO-ETF-CAPITULATION BTC-ETFs-~$4.5B-JUNE-OUTFLOWS-WORST-MONTH / $294.62M-OUT-JULY-1 / CUMULATIVE-SINCE-MAY-6-~$8.475B + CITI-CUTS-BTC-$112K-TO-$82K / ETH-$3,175-TO-$2,240 / NET-ETF-INFLOW-TO-ZERO + CRYPTO-COHORT BTC $62,613 +1.83% / ETH $1,758 +3.53% / SOL $82.16 +1.94% / XRP $1.13 +4.35% ALL-GREEN-ON-WARSH-DOVISH-BID but BTC-WELL-OFF-MAY-$73K-HIGH + IRAN-2026-CEASEFIRE JUNE-17-US-IRAN-MoU-60-DAY-EXTENSION / PEACE-NUCLEAR-TALKS-PAUSED-FOR-KHAMENEI-STATE-FUNERAL + FIFA-WORLD-CUP-2026-ON-US-SOIL + US-HEAT-WAVE-POSSIBLE-HOTTEST-JULY-4TH-ON-RECORD — DOW RECORD-CLOSE 52,900.07 +1.14% per TheStreet / CNBC.', category: 'general', related: 'TSLA' },
  { headline: 'Friday July 3 13:00 UTC BA-FOCUS-TAPE / INDUSTRIALS-DESK-WATCH — BOEING-INDUSTRIALS-RIDE-THE-DOW-RECORD as THURSDAY DOW-RECORD-CLOSE 52,900.07 +594.83 +1.14% led the tape / S&P-500 7,483.24 FLAT / NASDAQ 25,832.67 -0.8%-SEMI-DRAG the WEAK-JUNE-PAYROLLS-REVIVE-RATE-CUT-HOPES bid into AMERICAS-250TH-BIRTHDAY-LONG-WEEKEND + BA-CYCLICAL-BID-ON-RATE-CUT-HOPES-AND-DOW-LEADERSHIP + FED-CHAIR-KEVIN-WARSH-JULY-2-COMMENTS-EASE-INFLATION-FEARS after HOLDING-RATES-STEADY-AT-JUNE-DEBUT / TOOK-2026-CUT-OFF-THE-TABLE + HBM-MEMORY-SHORTAGE-DEEPENS (B300-NEEDS-8-HBM-CHIPS / DGX-B300 768-DRAM-DIES / RELIEF-NOT-UNTIL-LATE-2027-2028) + ARM -7%-PREMARKET CEO-RENE-HAAS-WARNS-SMARTPHONE-UNIT-GROWTH-FLIPS-NEGATIVE + OPENAI-ALTMAN-BINDING-CONSTRAINT-NOW-CHIPS AI-DATACENTERS-~70%-GLOBAL-MEMORY-2026 / DRAM-+50-55%-QoQ / STARGATE-SAMSUNG-SK-HYNIX-~900K-WAFER-STARTS-MO-~40%-GLOBAL + CRYPTO-ETF-CAPITULATION BTC-ETFs-~$4.5B-JUNE-OUTFLOWS-WORST-MONTH / $294.62M-OUT-JULY-1 / CUMULATIVE-SINCE-MAY-6-~$8.475B + CITI-CUTS-BTC-$112K-TO-$82K / ETH-$3,175-TO-$2,240 / NET-ETF-INFLOW-TO-ZERO + CRYPTO-COHORT BTC $62,613 +1.83% / ETH $1,758 +3.53% / SOL $82.16 +1.94% / XRP $1.13 +4.35% ALL-GREEN-ON-WARSH-DOVISH-BID but BTC-WELL-OFF-MAY-$73K-HIGH + IRAN-2026-CEASEFIRE JUNE-17-US-IRAN-MoU-60-DAY-EXTENSION / PEACE-NUCLEAR-TALKS-PAUSED-FOR-KHAMENEI-STATE-FUNERAL + FIFA-WORLD-CUP-2026-ON-US-SOIL + US-HEAT-WAVE-POSSIBLE-HOTTEST-JULY-4TH-ON-RECORD — DOW RECORD-CLOSE 52,900.07 +1.14% per TheStreet / CNBC.', category: 'general', related: 'BA' },
  { headline: 'Friday July 3 13:00 UTC COIN-FOCUS-TAPE / EXCHANGE-DESK-WATCH — COIN-CARRIES-THE-EXCHANGE-ANGLE into CRYPTO-ETF-CAPITULATION BTC-ETFs-~$4.5B-JUNE-OUTFLOWS-WORST-MONTH-SINCE-INCEPTION / $294.62M-OUT-JULY-1 / CUMULATIVE-SINCE-MAY-6-~$8.475B while THURSDAY DOW-RECORD-CLOSE 52,900.07 +594.83 +1.14% / S&P-500 7,483.24 FLAT / NASDAQ 25,832.67 -0.8%-SEMI-DRAG the WEAK-JUNE-PAYROLLS-REVIVE-RATE-CUT-HOPES bid into AMERICAS-250TH-BIRTHDAY-LONG-WEEKEND + FED-CHAIR-KEVIN-WARSH-JULY-2-COMMENTS-EASE-INFLATION-FEARS after HOLDING-RATES-STEADY-AT-JUNE-DEBUT / TOOK-2026-CUT-OFF-THE-TABLE + HBM-MEMORY-SHORTAGE-DEEPENS (B300-NEEDS-8-HBM-CHIPS / DGX-B300 768-DRAM-DIES / RELIEF-NOT-UNTIL-LATE-2027-2028) + ARM -7%-PREMARKET CEO-RENE-HAAS-WARNS-SMARTPHONE-UNIT-GROWTH-FLIPS-NEGATIVE + OPENAI-ALTMAN-BINDING-CONSTRAINT-NOW-CHIPS AI-DATACENTERS-~70%-GLOBAL-MEMORY-2026 / DRAM-+50-55%-QoQ / STARGATE-SAMSUNG-SK-HYNIX-~900K-WAFER-STARTS-MO-~40%-GLOBAL + CITI-CUTS-BTC-$112K-TO-$82K / ETH-$3,175-TO-$2,240 / NET-ETF-INFLOW-ASSUMPTION-TO-ZERO + CRYPTO-COHORT BTC $62,613 +1.83% / ETH $1,758 +3.53% / SOL $82.16 +1.94% / XRP $1.13 +4.35% ALL-GREEN-ON-WARSH-DOVISH-BID but BTC-WELL-OFF-MAY-$73K-HIGH + IRAN-2026-CEASEFIRE JUNE-17-US-IRAN-MoU-60-DAY-EXTENSION / PEACE-NUCLEAR-TALKS-PAUSED-FOR-KHAMENEI-STATE-FUNERAL + FIFA-WORLD-CUP-2026-ON-US-SOIL + US-HEAT-WAVE-POSSIBLE-HOTTEST-JULY-4TH-ON-RECORD — DOW RECORD-CLOSE 52,900.07 +1.14% per TheStreet / CNBC.', category: 'general', related: 'COIN' },
  { headline: 'Friday July 3 13:00 UTC AMD-FOCUS-TAPE / SEMI-DESK-WATCH — AMD-IN-THE-CHIP-COHORT-STRENGTH-VS-WEAKNESS-DEBATE as SEMIS-THE-LONE-JUL-2-LAGGARD dragged NASDAQ 25,832.67 -0.8% while THURSDAY DOW-RECORD-CLOSE 52,900.07 +594.83 +1.14% / S&P-500 7,483.24 FLAT the WEAK-JUNE-PAYROLLS-REVIVE-RATE-CUT-HOPES bid into AMERICAS-250TH-BIRTHDAY-LONG-WEEKEND + HBM-MEMORY-SHORTAGE-DEEPENS (B300-NEEDS-8-HBM-CHIPS / DGX-B300 768-DRAM-DIES / RELIEF-NOT-UNTIL-LATE-2027-2028) + FED-CHAIR-KEVIN-WARSH-JULY-2-COMMENTS-EASE-INFLATION-FEARS after HOLDING-RATES-STEADY-AT-JUNE-DEBUT / TOOK-2026-CUT-OFF-THE-TABLE + ARM -7%-PREMARKET CEO-RENE-HAAS-WARNS-SMARTPHONE-UNIT-GROWTH-FLIPS-NEGATIVE + OPENAI-ALTMAN-BINDING-CONSTRAINT-NOW-CHIPS AI-DATACENTERS-~70%-GLOBAL-MEMORY-2026 / DRAM-+50-55%-QoQ / STARGATE-SAMSUNG-SK-HYNIX-~900K-WAFER-STARTS-MO-~40%-GLOBAL + CRYPTO-ETF-CAPITULATION BTC-ETFs-~$4.5B-JUNE-OUTFLOWS-WORST-MONTH / $294.62M-OUT-JULY-1 / CUMULATIVE-SINCE-MAY-6-~$8.475B + CITI-CUTS-BTC-$112K-TO-$82K / ETH-$3,175-TO-$2,240 / NET-ETF-INFLOW-TO-ZERO + CRYPTO-COHORT BTC $62,613 +1.83% / ETH $1,758 +3.53% / SOL $82.16 +1.94% / XRP $1.13 +4.35% ALL-GREEN-ON-WARSH-DOVISH-BID but BTC-WELL-OFF-MAY-$73K-HIGH + IRAN-2026-CEASEFIRE JUNE-17-US-IRAN-MoU-60-DAY-EXTENSION / PEACE-NUCLEAR-TALKS-PAUSED-FOR-KHAMENEI-STATE-FUNERAL + FIFA-WORLD-CUP-2026-ON-US-SOIL + US-HEAT-WAVE-POSSIBLE-HOTTEST-JULY-4TH-ON-RECORD — DOW RECORD-CLOSE 52,900.07 +1.14% per TheStreet / CNBC.', category: 'general', related: 'AMD' },
  { headline: 'Friday July 3 13:00 UTC META-FOCUS-TAPE / MAG-7-WATCH — META-IN-THE-MAG-7-CROSSHAIRS after H1-2026-TECH-LED-BUT-MAG-7-SOLD-OFF-SHARPLY-LATE-JUNE with MSFT -22.9%-H1-THE-BIG-UNDERPERFORMER as THURSDAY DOW-RECORD-CLOSE 52,900.07 +594.83 +1.14% / S&P-500 7,483.24 FLAT / NASDAQ 25,832.67 -0.8%-SEMI-DRAG the WEAK-JUNE-PAYROLLS-REVIVE-RATE-CUT-HOPES bid into AMERICAS-250TH-BIRTHDAY-LONG-WEEKEND + FED-CHAIR-KEVIN-WARSH-JULY-2-COMMENTS-EASE-INFLATION-FEARS after HOLDING-RATES-STEADY-AT-JUNE-DEBUT / TOOK-2026-CUT-OFF-THE-TABLE + HBM-MEMORY-SHORTAGE-DEEPENS (B300-NEEDS-8-HBM-CHIPS / DGX-B300 768-DRAM-DIES / RELIEF-NOT-UNTIL-LATE-2027-2028) + ARM -7%-PREMARKET CEO-RENE-HAAS-WARNS-SMARTPHONE-UNIT-GROWTH-FLIPS-NEGATIVE + OPENAI-ALTMAN-BINDING-CONSTRAINT-NOW-CHIPS AI-DATACENTERS-~70%-GLOBAL-MEMORY-2026 / DRAM-+50-55%-QoQ / STARGATE-SAMSUNG-SK-HYNIX-~900K-WAFER-STARTS-MO-~40%-GLOBAL + CRYPTO-ETF-CAPITULATION BTC-ETFs-~$4.5B-JUNE-OUTFLOWS-WORST-MONTH / $294.62M-OUT-JULY-1 / CUMULATIVE-SINCE-MAY-6-~$8.475B + CITI-CUTS-BTC-$112K-TO-$82K / ETH-$3,175-TO-$2,240 / NET-ETF-INFLOW-TO-ZERO + CRYPTO-COHORT BTC $62,613 +1.83% / ETH $1,758 +3.53% / SOL $82.16 +1.94% / XRP $1.13 +4.35% ALL-GREEN-ON-WARSH-DOVISH-BID but BTC-WELL-OFF-MAY-$73K-HIGH + IRAN-2026-CEASEFIRE JUNE-17-US-IRAN-MoU-60-DAY-EXTENSION / PEACE-NUCLEAR-TALKS-PAUSED-FOR-KHAMENEI-STATE-FUNERAL + FIFA-WORLD-CUP-2026-ON-US-SOIL + US-HEAT-WAVE-POSSIBLE-HOTTEST-JULY-4TH-ON-RECORD — DOW RECORD-CLOSE 52,900.07 +1.14% per TheStreet / CNBC.', category: 'general', related: 'META' },
  { headline: 'Friday July 3 13:00 UTC MSTR-FOCUS-TAPE / TREASURY-DESK-WATCH — MSTR-CARRIES-THE-BITCOIN-TREASURY-ANGLE into CRYPTO-ETF-CAPITULATION BTC-ETFs-~$4.5B-JUNE-OUTFLOWS-WORST-MONTH-SINCE-INCEPTION / $294.62M-OUT-JULY-1 / CUMULATIVE-SINCE-MAY-6-~$8.475B and CITI-CUTS-BTC-$112K-TO-$82K / ETH-$3,175-TO-$2,240 / NET-ETF-INFLOW-ASSUMPTION-TO-ZERO while THURSDAY DOW-RECORD-CLOSE 52,900.07 +594.83 +1.14% / S&P-500 7,483.24 FLAT / NASDAQ 25,832.67 -0.8%-SEMI-DRAG the WEAK-JUNE-PAYROLLS-REVIVE-RATE-CUT-HOPES bid into AMERICAS-250TH-BIRTHDAY-LONG-WEEKEND + FED-CHAIR-KEVIN-WARSH-JULY-2-COMMENTS-EASE-INFLATION-FEARS after HOLDING-RATES-STEADY-AT-JUNE-DEBUT / TOOK-2026-CUT-OFF-THE-TABLE + HBM-MEMORY-SHORTAGE-DEEPENS (B300-NEEDS-8-HBM-CHIPS / DGX-B300 768-DRAM-DIES / RELIEF-NOT-UNTIL-LATE-2027-2028) + ARM -7%-PREMARKET CEO-RENE-HAAS-WARNS-SMARTPHONE-UNIT-GROWTH-FLIPS-NEGATIVE + OPENAI-ALTMAN-BINDING-CONSTRAINT-NOW-CHIPS AI-DATACENTERS-~70%-GLOBAL-MEMORY-2026 / DRAM-+50-55%-QoQ / STARGATE-SAMSUNG-SK-HYNIX-~900K-WAFER-STARTS-MO-~40%-GLOBAL + CRYPTO-COHORT BTC $62,613 +1.83% / ETH $1,758 +3.53% / SOL $82.16 +1.94% / XRP $1.13 +4.35% ALL-GREEN-ON-WARSH-DOVISH-BID but BTC-WELL-OFF-MAY-$73K-HIGH + IRAN-2026-CEASEFIRE JUNE-17-US-IRAN-MoU-60-DAY-EXTENSION / PEACE-NUCLEAR-TALKS-PAUSED-FOR-KHAMENEI-STATE-FUNERAL + FIFA-WORLD-CUP-2026-ON-US-SOIL + US-HEAT-WAVE-POSSIBLE-HOTTEST-JULY-4TH-ON-RECORD — DOW RECORD-CLOSE 52,900.07 +1.14% per TheStreet / CNBC.', category: 'general', related: 'MSTR' },
  { headline: 'Friday July 3 13:00 UTC BTC-FOCUS-TAPE / CRYPTO-DESK-WATCH — BTC-+~2.38%-ON-JUL-2 on WARSH-DOVISH-COMMENTS-AND-WEAK-PAYROLLS yet CRYPTO-ETF-CAPITULATION-GRINDS-ON BTC-ETFs-~$4.5B-JUNE-OUTFLOWS-WORST-MONTH-SINCE-INCEPTION / $294.62M-OUT-JULY-1 / CUMULATIVE-SINCE-MAY-6-~$8.475B and CITI-CUTS-BTC-$112K-TO-$82K / ETH-$3,175-TO-$2,240 / NET-ETF-INFLOW-ASSUMPTION-TO-ZERO while THURSDAY DOW-RECORD-CLOSE 52,900.07 +594.83 +1.14% / S&P-500 7,483.24 FLAT / NASDAQ 25,832.67 -0.8%-SEMI-DRAG the WEAK-JUNE-PAYROLLS-REVIVE-RATE-CUT-HOPES bid into AMERICAS-250TH-BIRTHDAY-LONG-WEEKEND + FED-CHAIR-KEVIN-WARSH-JULY-2-COMMENTS-EASE-INFLATION-FEARS after HOLDING-RATES-STEADY-AT-JUNE-DEBUT / TOOK-2026-CUT-OFF-THE-TABLE + HBM-MEMORY-SHORTAGE-DEEPENS (B300-NEEDS-8-HBM-CHIPS / DGX-B300 768-DRAM-DIES / RELIEF-NOT-UNTIL-LATE-2027-2028) + OPENAI-ALTMAN-BINDING-CONSTRAINT-NOW-CHIPS AI-DATACENTERS-~70%-GLOBAL-MEMORY-2026 / DRAM-+50-55%-QoQ / STARGATE-SAMSUNG-SK-HYNIX-~900K-WAFER-STARTS-MO-~40%-GLOBAL + CRYPTO-COHORT BTC $62,613 +1.83% / ETH $1,758 +3.53% / SOL $82.16 +1.94% / XRP $1.13 +4.35% ALL-GREEN-ON-WARSH-DOVISH-BID but BTC-WELL-OFF-MAY-$73K-HIGH + IRAN-2026-CEASEFIRE JUNE-17-US-IRAN-MoU-60-DAY-EXTENSION / PEACE-NUCLEAR-TALKS-PAUSED-FOR-KHAMENEI-STATE-FUNERAL + FIFA-WORLD-CUP-2026-ON-US-SOIL + US-HEAT-WAVE-POSSIBLE-HOTTEST-JULY-4TH-ON-RECORD — DOW RECORD-CLOSE 52,900.07 +1.14% per TheStreet / CNBC.', category: 'general', related: 'BTC' },
  { headline: 'Friday July 3 13:00 UTC ETH-FOCUS-TAPE / CRYPTO-DESK-WATCH — ETHER-ETFs-ALSO-BLEEDING-INTO-JULY as CRYPTO-ETF-CAPITULATION-GRINDS-ON BTC-ETFs-~$4.5B-JUNE-OUTFLOWS-WORST-MONTH-SINCE-INCEPTION / $294.62M-OUT-JULY-1 / CUMULATIVE-SINCE-MAY-6-~$8.475B and CITI-CUTS-ETH-$3,175-TO-$2,240 / BTC-$112K-TO-$82K / NET-ETF-INFLOW-ASSUMPTION-TO-ZERO while THURSDAY DOW-RECORD-CLOSE 52,900.07 +594.83 +1.14% / S&P-500 7,483.24 FLAT / NASDAQ 25,832.67 -0.8%-SEMI-DRAG the WEAK-JUNE-PAYROLLS-REVIVE-RATE-CUT-HOPES bid into AMERICAS-250TH-BIRTHDAY-LONG-WEEKEND + FED-CHAIR-KEVIN-WARSH-JULY-2-COMMENTS-EASE-INFLATION-FEARS after HOLDING-RATES-STEADY-AT-JUNE-DEBUT / TOOK-2026-CUT-OFF-THE-TABLE + HBM-MEMORY-SHORTAGE-DEEPENS (B300-NEEDS-8-HBM-CHIPS / DGX-B300 768-DRAM-DIES / RELIEF-NOT-UNTIL-LATE-2027-2028) + OPENAI-ALTMAN-BINDING-CONSTRAINT-NOW-CHIPS AI-DATACENTERS-~70%-GLOBAL-MEMORY-2026 / DRAM-+50-55%-QoQ / STARGATE-SAMSUNG-SK-HYNIX-~900K-WAFER-STARTS-MO-~40%-GLOBAL + CRYPTO-COHORT BTC $62,613 +1.83% / ETH $1,758 +3.53% / SOL $82.16 +1.94% / XRP $1.13 +4.35% ALL-GREEN-ON-WARSH-DOVISH-BID but ETH-WELL-OFF-SPRING-HIGHS + IRAN-2026-CEASEFIRE JUNE-17-US-IRAN-MoU-60-DAY-EXTENSION / PEACE-NUCLEAR-TALKS-PAUSED-FOR-KHAMENEI-STATE-FUNERAL + FIFA-WORLD-CUP-2026-ON-US-SOIL + US-HEAT-WAVE-POSSIBLE-HOTTEST-JULY-4TH-ON-RECORD — DOW RECORD-CLOSE 52,900.07 +1.14% per TheStreet / CNBC.', category: 'general', related: 'ETH' },
  { headline: 'Friday July 3 13:00 UTC SOL-FOCUS-TAPE / CRYPTO-DESK-WATCH — SOL-JOINS-THE-GREEN-COHORT-ON-JULY-2-WARSH-DOVISH-BID even as CRYPTO-ETF-CAPITULATION-GRINDS-ON BTC-ETFs-~$4.5B-JUNE-OUTFLOWS-WORST-MONTH-SINCE-INCEPTION / $294.62M-OUT-JULY-1 / CUMULATIVE-SINCE-MAY-6-~$8.475B and CITI-CUTS-BTC-$112K-TO-$82K / ETH-$3,175-TO-$2,240 / NET-ETF-INFLOW-ASSUMPTION-TO-ZERO while THURSDAY DOW-RECORD-CLOSE 52,900.07 +594.83 +1.14% / S&P-500 7,483.24 FLAT / NASDAQ 25,832.67 -0.8%-SEMI-DRAG the WEAK-JUNE-PAYROLLS-REVIVE-RATE-CUT-HOPES bid into AMERICAS-250TH-BIRTHDAY-LONG-WEEKEND + FED-CHAIR-KEVIN-WARSH-JULY-2-COMMENTS-EASE-INFLATION-FEARS after HOLDING-RATES-STEADY-AT-JUNE-DEBUT / TOOK-2026-CUT-OFF-THE-TABLE + HBM-MEMORY-SHORTAGE-DEEPENS (B300-NEEDS-8-HBM-CHIPS / DGX-B300 768-DRAM-DIES / RELIEF-NOT-UNTIL-LATE-2027-2028) + OPENAI-ALTMAN-BINDING-CONSTRAINT-NOW-CHIPS AI-DATACENTERS-~70%-GLOBAL-MEMORY-2026 / DRAM-+50-55%-QoQ / STARGATE-SAMSUNG-SK-HYNIX-~900K-WAFER-STARTS-MO-~40%-GLOBAL + CRYPTO-COHORT BTC $62,613 +1.83% / ETH $1,758 +3.53% / SOL $82.16 +1.94% / XRP $1.13 +4.35% ALL-GREEN-ON-WARSH-DOVISH-BID but BROAD-COMPLEX-WELL-OFF-SPRING-HIGHS + IRAN-2026-CEASEFIRE JUNE-17-US-IRAN-MoU-60-DAY-EXTENSION / PEACE-NUCLEAR-TALKS-PAUSED-FOR-KHAMENEI-STATE-FUNERAL + FIFA-WORLD-CUP-2026-ON-US-SOIL + US-HEAT-WAVE-POSSIBLE-HOTTEST-JULY-4TH-ON-RECORD — DOW RECORD-CLOSE 52,900.07 +1.14% per TheStreet / CNBC.', category: 'general', related: 'SOL' },
  { headline: 'Friday July 3 13:00 UTC XRP-FOCUS-TAPE / CRYPTO-DESK-WATCH — XRP-THE-BIGGEST-COHORT-GAINER-ON-JULY-2-WARSH-DOVISH-BID even as CRYPTO-ETF-CAPITULATION-GRINDS-ON BTC-ETFs-~$4.5B-JUNE-OUTFLOWS-WORST-MONTH-SINCE-INCEPTION / $294.62M-OUT-JULY-1 / CUMULATIVE-SINCE-MAY-6-~$8.475B and CITI-CUTS-BTC-$112K-TO-$82K / ETH-$3,175-TO-$2,240 / NET-ETF-INFLOW-ASSUMPTION-TO-ZERO while THURSDAY DOW-RECORD-CLOSE 52,900.07 +594.83 +1.14% / S&P-500 7,483.24 FLAT / NASDAQ 25,832.67 -0.8%-SEMI-DRAG the WEAK-JUNE-PAYROLLS-REVIVE-RATE-CUT-HOPES bid into AMERICAS-250TH-BIRTHDAY-LONG-WEEKEND + FED-CHAIR-KEVIN-WARSH-JULY-2-COMMENTS-EASE-INFLATION-FEARS after HOLDING-RATES-STEADY-AT-JUNE-DEBUT / TOOK-2026-CUT-OFF-THE-TABLE + HBM-MEMORY-SHORTAGE-DEEPENS (B300-NEEDS-8-HBM-CHIPS / DGX-B300 768-DRAM-DIES / RELIEF-NOT-UNTIL-LATE-2027-2028) + OPENAI-ALTMAN-BINDING-CONSTRAINT-NOW-CHIPS AI-DATACENTERS-~70%-GLOBAL-MEMORY-2026 / DRAM-+50-55%-QoQ / STARGATE-SAMSUNG-SK-HYNIX-~900K-WAFER-STARTS-MO-~40%-GLOBAL + CRYPTO-COHORT BTC $62,613 +1.83% / ETH $1,758 +3.53% / SOL $82.16 +1.94% / XRP $1.13 +4.35% ALL-GREEN-ON-WARSH-DOVISH-BID but BROAD-COMPLEX-WELL-OFF-SPRING-HIGHS + IRAN-2026-CEASEFIRE JUNE-17-US-IRAN-MoU-60-DAY-EXTENSION / PEACE-NUCLEAR-TALKS-PAUSED-FOR-KHAMENEI-STATE-FUNERAL + FIFA-WORLD-CUP-2026-ON-US-SOIL + US-HEAT-WAVE-POSSIBLE-HOTTEST-JULY-4TH-ON-RECORD — DOW RECORD-CLOSE 52,900.07 +1.14% per TheStreet / CNBC.', category: 'general', related: 'XRP' },
  { headline: 'Macro Friday July 3 13:00 UTC WORLD-DESK-TAPE / IRAN-WATCH — IRAN-2026-CEASEFIRE-HOLDS SUPREME-LEADER-ALI-KHAMENEI-KILLED-IN-FEB-28-2026-STRIKES / MOJTABA-KHAMENEI-NAMED-SUCCESSOR / JUNE-17-US-IRAN-MoU-60-DAY-CEASEFIRE-EXTENSION / PEACE-AND-NUCLEAR-TALKS-PAUSED-FOR-DAYSLONG-STATE-FUNERAL as markets ran THURSDAY DOW-RECORD-CLOSE 52,900.07 +594.83 +1.14% / S&P-500 7,483.24 FLAT / NASDAQ 25,832.67 -0.8%-SEMI-DRAG the WEAK-JUNE-PAYROLLS-REVIVE-RATE-CUT-HOPES bid into AMERICAS-250TH-BIRTHDAY-LONG-WEEKEND + FED-CHAIR-KEVIN-WARSH-JULY-2-COMMENTS-EASE-INFLATION-FEARS after HOLDING-RATES-STEADY-AT-JUNE-DEBUT / TOOK-2026-CUT-OFF-THE-TABLE + HBM-MEMORY-SHORTAGE-DEEPENS (B300-NEEDS-8-HBM-CHIPS / DGX-B300 768-DRAM-DIES / RELIEF-NOT-UNTIL-LATE-2027-2028) + ARM -7%-PREMARKET CEO-RENE-HAAS-WARNS-SMARTPHONE-UNIT-GROWTH-FLIPS-NEGATIVE + OPENAI-ALTMAN-BINDING-CONSTRAINT-NOW-CHIPS AI-DATACENTERS-~70%-GLOBAL-MEMORY-2026 / DRAM-+50-55%-QoQ / STARGATE-SAMSUNG-SK-HYNIX-~900K-WAFER-STARTS-MO-~40%-GLOBAL + CRYPTO-ETF-CAPITULATION BTC-ETFs-~$4.5B-JUNE-OUTFLOWS-WORST-MONTH / $294.62M-OUT-JULY-1 / CUMULATIVE-SINCE-MAY-6-~$8.475B + CITI-CUTS-BTC-$112K-TO-$82K / ETH-$3,175-TO-$2,240 / NET-ETF-INFLOW-TO-ZERO + CRYPTO-COHORT BTC $62,613 +1.83% / ETH $1,758 +3.53% / SOL $82.16 +1.94% / XRP $1.13 +4.35% ALL-GREEN-ON-WARSH-DOVISH-BID but BTC-WELL-OFF-MAY-$73K-HIGH + FIFA-WORLD-CUP-2026-ON-US-SOIL + US-HEAT-WAVE-POSSIBLE-HOTTEST-JULY-4TH-ON-RECORD — DOW RECORD-CLOSE 52,900.07 +1.14% per TheStreet / CNBC.', category: 'general', related: '' },
  { headline: 'Macro Friday July 3 13:00 UTC WORLD-DESK-TAPE / VATICAN-WATCH — VATICAN-DECLARES-SSPX-IN-SCHISM the headline faith-and-geopolitics story alongside VENEZUELA-EARTHQUAKE-RECOVERY-ONGOING as markets ran THURSDAY DOW-RECORD-CLOSE 52,900.07 +594.83 +1.14% / S&P-500 7,483.24 FLAT / NASDAQ 25,832.67 -0.8%-SEMI-DRAG the WEAK-JUNE-PAYROLLS-REVIVE-RATE-CUT-HOPES bid into AMERICAS-250TH-BIRTHDAY-LONG-WEEKEND + FED-CHAIR-KEVIN-WARSH-JULY-2-COMMENTS-EASE-INFLATION-FEARS after HOLDING-RATES-STEADY-AT-JUNE-DEBUT / TOOK-2026-CUT-OFF-THE-TABLE + HBM-MEMORY-SHORTAGE-DEEPENS (B300-NEEDS-8-HBM-CHIPS / DGX-B300 768-DRAM-DIES / RELIEF-NOT-UNTIL-LATE-2027-2028) + ARM -7%-PREMARKET CEO-RENE-HAAS-WARNS-SMARTPHONE-UNIT-GROWTH-FLIPS-NEGATIVE + OPENAI-ALTMAN-BINDING-CONSTRAINT-NOW-CHIPS AI-DATACENTERS-~70%-GLOBAL-MEMORY-2026 / DRAM-+50-55%-QoQ / STARGATE-SAMSUNG-SK-HYNIX-~900K-WAFER-STARTS-MO-~40%-GLOBAL + CRYPTO-ETF-CAPITULATION BTC-ETFs-~$4.5B-JUNE-OUTFLOWS-WORST-MONTH / $294.62M-OUT-JULY-1 / CUMULATIVE-SINCE-MAY-6-~$8.475B + CITI-CUTS-BTC-$112K-TO-$82K / ETH-$3,175-TO-$2,240 / NET-ETF-INFLOW-TO-ZERO + CRYPTO-COHORT BTC $62,613 +1.83% / ETH $1,758 +3.53% / SOL $82.16 +1.94% / XRP $1.13 +4.35% ALL-GREEN-ON-WARSH-DOVISH-BID but BTC-WELL-OFF-MAY-$73K-HIGH + IRAN-2026-CEASEFIRE JUNE-17-US-IRAN-MoU-60-DAY-EXTENSION / PEACE-NUCLEAR-TALKS-PAUSED-FOR-KHAMENEI-STATE-FUNERAL + FIFA-WORLD-CUP-2026-ON-US-SOIL + US-HEAT-WAVE-POSSIBLE-HOTTEST-JULY-4TH-ON-RECORD — DOW RECORD-CLOSE 52,900.07 +1.14% per TheStreet / CNBC.', category: 'general', related: '' },
  { headline: 'Macro Friday July 3 13:00 UTC WORLD-DESK-TAPE / DISASTER-WATCH — VENEZUELA-EARTHQUAKE-RECOVERY-ONGOING and US-HEAT-WAVE-POSSIBLE-HOTTEST-JULY-4TH-ON-RECORD the humanitarian and weather headlines as markets ran THURSDAY DOW-RECORD-CLOSE 52,900.07 +594.83 +1.14% / S&P-500 7,483.24 FLAT / NASDAQ 25,832.67 -0.8%-SEMI-DRAG the WEAK-JUNE-PAYROLLS-REVIVE-RATE-CUT-HOPES bid into AMERICAS-250TH-BIRTHDAY-LONG-WEEKEND + FED-CHAIR-KEVIN-WARSH-JULY-2-COMMENTS-EASE-INFLATION-FEARS after HOLDING-RATES-STEADY-AT-JUNE-DEBUT / TOOK-2026-CUT-OFF-THE-TABLE + HBM-MEMORY-SHORTAGE-DEEPENS (B300-NEEDS-8-HBM-CHIPS / DGX-B300 768-DRAM-DIES / RELIEF-NOT-UNTIL-LATE-2027-2028) + ARM -7%-PREMARKET CEO-RENE-HAAS-WARNS-SMARTPHONE-UNIT-GROWTH-FLIPS-NEGATIVE + OPENAI-ALTMAN-BINDING-CONSTRAINT-NOW-CHIPS AI-DATACENTERS-~70%-GLOBAL-MEMORY-2026 / DRAM-+50-55%-QoQ / STARGATE-SAMSUNG-SK-HYNIX-~900K-WAFER-STARTS-MO-~40%-GLOBAL + CRYPTO-ETF-CAPITULATION BTC-ETFs-~$4.5B-JUNE-OUTFLOWS-WORST-MONTH / $294.62M-OUT-JULY-1 / CUMULATIVE-SINCE-MAY-6-~$8.475B + CITI-CUTS-BTC-$112K-TO-$82K / ETH-$3,175-TO-$2,240 / NET-ETF-INFLOW-TO-ZERO + CRYPTO-COHORT BTC $62,613 +1.83% / ETH $1,758 +3.53% / SOL $82.16 +1.94% / XRP $1.13 +4.35% ALL-GREEN-ON-WARSH-DOVISH-BID but BTC-WELL-OFF-MAY-$73K-HIGH + IRAN-2026-CEASEFIRE JUNE-17-US-IRAN-MoU-60-DAY-EXTENSION / PEACE-NUCLEAR-TALKS-PAUSED-FOR-KHAMENEI-STATE-FUNERAL + FIFA-WORLD-CUP-2026-ON-US-SOIL — DOW RECORD-CLOSE 52,900.07 +1.14% per TheStreet / CNBC.', category: 'general', related: '' },
  { headline: 'Macro Friday July 3 13:00 UTC WORLD-DESK-TAPE / SPORTS-WATCH — FIFA-WORLD-CUP-2026-ON-US-SOIL rolls on EGYPT-VS-AUSTRALIA-R32-AT-ARLINGTON-TX into the AMERICAS-250TH-BIRTHDAY-LONG-JULY-4-WEEKEND as markets ran THURSDAY DOW-RECORD-CLOSE 52,900.07 +594.83 +1.14% / S&P-500 7,483.24 FLAT / NASDAQ 25,832.67 -0.8%-SEMI-DRAG the WEAK-JUNE-PAYROLLS-REVIVE-RATE-CUT-HOPES bid + FED-CHAIR-KEVIN-WARSH-JULY-2-COMMENTS-EASE-INFLATION-FEARS after HOLDING-RATES-STEADY-AT-JUNE-DEBUT / TOOK-2026-CUT-OFF-THE-TABLE + HBM-MEMORY-SHORTAGE-DEEPENS (B300-NEEDS-8-HBM-CHIPS / DGX-B300 768-DRAM-DIES / RELIEF-NOT-UNTIL-LATE-2027-2028) + ARM -7%-PREMARKET CEO-RENE-HAAS-WARNS-SMARTPHONE-UNIT-GROWTH-FLIPS-NEGATIVE + OPENAI-ALTMAN-BINDING-CONSTRAINT-NOW-CHIPS AI-DATACENTERS-~70%-GLOBAL-MEMORY-2026 / DRAM-+50-55%-QoQ / STARGATE-SAMSUNG-SK-HYNIX-~900K-WAFER-STARTS-MO-~40%-GLOBAL + CRYPTO-ETF-CAPITULATION BTC-ETFs-~$4.5B-JUNE-OUTFLOWS-WORST-MONTH / $294.62M-OUT-JULY-1 / CUMULATIVE-SINCE-MAY-6-~$8.475B + CITI-CUTS-BTC-$112K-TO-$82K / ETH-$3,175-TO-$2,240 / NET-ETF-INFLOW-TO-ZERO + CRYPTO-COHORT BTC $62,613 +1.83% / ETH $1,758 +3.53% / SOL $82.16 +1.94% / XRP $1.13 +4.35% ALL-GREEN-ON-WARSH-DOVISH-BID but BTC-WELL-OFF-MAY-$73K-HIGH + IRAN-2026-CEASEFIRE JUNE-17-US-IRAN-MoU-60-DAY-EXTENSION / PEACE-NUCLEAR-TALKS-PAUSED-FOR-KHAMENEI-STATE-FUNERAL + US-HEAT-WAVE-POSSIBLE-HOTTEST-JULY-4TH-ON-RECORD — DOW RECORD-CLOSE 52,900.07 +1.14% per TheStreet / CNBC.', category: 'general', related: '' },
  { headline: 'Macro Friday July 3 13:00 UTC WORLD-DESK-TAPE / HOLIDAY-WEATHER-WATCH — US-HEAT-WAVE-POSSIBLE-HOTTEST-JULY-4TH-ON-RECORD blankets the AMERICAS-250TH-BIRTHDAY-LONG-WEEKEND as markets ran THURSDAY DOW-RECORD-CLOSE 52,900.07 +594.83 +1.14% / S&P-500 7,483.24 FLAT / NASDAQ 25,832.67 -0.8%-SEMI-DRAG the WEAK-JUNE-PAYROLLS-REVIVE-RATE-CUT-HOPES bid + FED-CHAIR-KEVIN-WARSH-JULY-2-COMMENTS-EASE-INFLATION-FEARS after HOLDING-RATES-STEADY-AT-JUNE-DEBUT / TOOK-2026-CUT-OFF-THE-TABLE + H1-2026-TECH-LED-BUT-MAG-7-SOLD-OFF-SHARPLY-LATE-JUNE + HBM-MEMORY-SHORTAGE-DEEPENS (B300-NEEDS-8-HBM-CHIPS / DGX-B300 768-DRAM-DIES / RELIEF-NOT-UNTIL-LATE-2027-2028) + ARM -7%-PREMARKET CEO-RENE-HAAS-WARNS-SMARTPHONE-UNIT-GROWTH-FLIPS-NEGATIVE + OPENAI-ALTMAN-BINDING-CONSTRAINT-NOW-CHIPS AI-DATACENTERS-~70%-GLOBAL-MEMORY-2026 / DRAM-+50-55%-QoQ / STARGATE-SAMSUNG-SK-HYNIX-~900K-WAFER-STARTS-MO-~40%-GLOBAL + CRYPTO-ETF-CAPITULATION BTC-ETFs-~$4.5B-JUNE-OUTFLOWS-WORST-MONTH / $294.62M-OUT-JULY-1 / CUMULATIVE-SINCE-MAY-6-~$8.475B + CITI-CUTS-BTC-$112K-TO-$82K / ETH-$3,175-TO-$2,240 / NET-ETF-INFLOW-TO-ZERO + CRYPTO-COHORT BTC $62,613 +1.83% / ETH $1,758 +3.53% / SOL $82.16 +1.94% / XRP $1.13 +4.35% ALL-GREEN-ON-WARSH-DOVISH-BID but BTC-WELL-OFF-MAY-$73K-HIGH + IRAN-2026-CEASEFIRE JUNE-17-US-IRAN-MoU-60-DAY-EXTENSION / PEACE-NUCLEAR-TALKS-PAUSED-FOR-KHAMENEI-STATE-FUNERAL + VATICAN-DECLARES-SSPX-IN-SCHISM + FIFA-WORLD-CUP-2026-ON-US-SOIL — DOW RECORD-CLOSE 52,900.07 +1.14% per TheStreet / CNBC.', category: 'general', related: '' },
];

// Get date string in YYYY-MM-DD format
function getDateString(daysAgo = 0) {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  return date.toISOString().split('T')[0];
}

// Fetch company-specific news
async function fetchCompanyNews(symbol: string): Promise<any[]> {
  try {
    const to = getDateString(0);
    const from = getDateString(3); // Last 3 days
    const response = await fetch(
      `https://finnhub.io/api/v1/company-news?symbol=${symbol}&from=${from}&to=${to}&token=${FINNHUB_API_KEY}`
    );
    if (!response.ok) return [];
    const data = await response.json();
    // Take top 2 per company, tag with ticker
    return data.slice(0, 2).map((item: any) => ({
      ...item,
      related: symbol, // Ensure ticker is set
    }));
  } catch {
    return [];
  }
}

export async function GET() {
  // If no API key, return fallback immediately
  if (!process.env.FINNHUB_API_KEY) {
    return NextResponse.json({
      headlines: FALLBACK_NEWS,
      source: 'fallback',
      message: 'Set FINNHUB_API_KEY in .env.local for live news'
    });
  }

  const now = Date.now();
  if (cachedHeadlines && (now - cacheTimestamp) < CACHE_DURATION) {
    return NextResponse.json({
      headlines: cachedHeadlines,
      source: 'finnhub',
      cached: true,
    });
  }

  try {
    // Fetch general news, crypto news, and company-specific news in parallel
    const [generalResponse, cryptoResponse, ...companyNews] = await Promise.all([
      fetch(
        `https://finnhub.io/api/v1/news?category=general&token=${FINNHUB_API_KEY}`
      ),
      fetch(
        `https://finnhub.io/api/v1/news?category=crypto&token=${FINNHUB_API_KEY}`
      ),
      ...KEY_TICKERS.slice(0, 5).map(ticker => fetchCompanyNews(ticker)) // Limit to 5 to avoid rate limits
    ]);

    if (!generalResponse.ok) {
      throw new Error(`Finnhub API error: ${generalResponse.status}`);
    }

    const generalData = await generalResponse.json();
    const cryptoData = cryptoResponse.ok ? await cryptoResponse.json() : [];

    // Combine all news
    const allNews: any[] = [];

    // Add crypto news with ticker detection (using word boundaries to avoid false matches)
    const cryptoPatterns = [
      { pattern: /\b(xrp|ripple)\b/i, ticker: 'XRP' },      // Check XRP first (less common words)
      { pattern: /\b(solana|sol)\b/i, ticker: 'SOL' },       // SOL as word boundary
      { pattern: /\b(doge|dogecoin)\b/i, ticker: 'DOGE' },
      { pattern: /\b(ethereum|eth)\b/i, ticker: 'ETH' },     // ETH as word boundary
      { pattern: /\b(bitcoin|btc)\b/i, ticker: 'BTC' },      // BTC last (most common, catch-all)
    ];

    cryptoData.slice(0, 6).forEach((item: any) => {
      const headline = item.headline || '';
      // Find matching crypto ticker
      let ticker = '';
      for (const { pattern, ticker: t } of cryptoPatterns) {
        if (pattern.test(headline)) {
          ticker = t;
          break;
        }
      }

      allNews.push({
        headline: item.headline,
        category: 'crypto',
        related: ticker,
        source: item.source,
        url: item.url,
        image: item.image,
        datetime: item.datetime,
      });
    });

    // Add company news (they have tickers)
    companyNews.flat().forEach((item: any) => {
      if (item && item.headline) {
        allNews.push({
          headline: item.headline,
          category: item.category || 'company',
          related: item.related || '',
          source: item.source,
          url: item.url,
          image: item.image,
          datetime: item.datetime,
        });
      }
    });

    // Add general news
    generalData.slice(0, 10).forEach((item: any) => {
      allNews.push({
        headline: item.headline,
        category: item.category || 'general',
        related: item.related || '',
        source: item.source,
        url: item.url,
        image: item.image,
        datetime: item.datetime,
      });
    });

    // Deduplicate by headline
    const seen = new Set();
    const unique = allNews.filter(item => {
      const key = item.headline.toLowerCase().slice(0, 50);
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    });

    // Separate news with tickers from general news
    const withTickers = unique.filter(item => item.related && item.related.length > 0);
    const withoutTickers = unique.filter(item => !item.related || item.related.length === 0);

    // Sort each group by datetime
    withTickers.sort((a, b) => (b.datetime || 0) - (a.datetime || 0));
    withoutTickers.sort((a, b) => (b.datetime || 0) - (a.datetime || 0));

    // Take up to 5 ticker news + fill rest with general news (total 8)
    const sorted = [
      ...withTickers.slice(0, 5),
      ...withoutTickers.slice(0, 8 - Math.min(withTickers.length, 5))
    ];

    cachedHeadlines = sorted;
    cacheTimestamp = now;

    return NextResponse.json({
      headlines: sorted,
      source: 'finnhub',
      cached: false,
    });
  } catch (error) {
    console.error('News API error:', error);
    if (cachedHeadlines) {
      return NextResponse.json({
        headlines: cachedHeadlines,
        source: 'finnhub',
        cached: true,
        stale: true,
      });
    }
    return NextResponse.json({
      headlines: FALLBACK_NEWS,
      source: 'fallback',
      error: 'Failed to fetch live news',
    });
  }
}
